package com.digitalpet.ui.theme

import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Every file in `design-system/` is a **copy of a design-project file**, and
 * this is the list of which one.
 *
 * **The hole this fills was found by being asked a question, not by a test.**
 * `strings.txt` and `components.txt` began life as manifests written on the
 * code's side — they existed nowhere in the design project. That made
 * `StringSyncTest` and `ComponentRosterTest` weaker than they read: they could
 * catch the *code* drifting from the *manifest*, and never the manifest drifting
 * from the design.
 *
 * **It cost exactly what you would expect, on 2026-08-09.** The models chip was
 * hand-edited to "Models loaded" in the design gallery. Nothing failed. The
 * manifest said "Models", the code said "Models", the two agreed with each other
 * while both disagreed with the design, and `design-sync.sh` reported green
 * throughout. The edit was found because somebody said where to look.
 *
 * Both manifests now live in the design project and `design-system/` holds
 * copies, so a pull produces a real file diff the way the token CSS always did.
 *
 * ### What this test actually checks
 *
 * Not the contents — the other tests do that. It checks the **claim of
 * provenance**: that every file here is one the pull script knows how to
 * refresh. A file in this directory with no upstream is the thing that went
 * wrong, and it is invisible by construction — it looks exactly like a vendored
 * file until somebody asks where it came from.
 */
class VendoredCopyTest {

    /**
     * Vendored path → its path in the design project.
     *
     * They are identical today, and the mapping is written out anyway: the two
     * `.txt` manifests sit at the project root while their copies sit under
     * `design-system/`, so "same path" is already only true by accident of that
     * directory being the mount point. Stating it means a future move is a line
     * here rather than a silent mismatch.
     */
    private val vendored = mapOf(
        "tokens/colors.css" to "tokens/colors.css",
        "tokens/spacing.css" to "tokens/spacing.css",
        "tokens/shape.css" to "tokens/shape.css",
        "tokens/typography.css" to "tokens/typography.css",
        "strings.txt" to "strings.txt",
        "components.txt" to "components.txt",
        // v9 face sets. One file per set, and the previews generated from them
        // — the design project holds the same paths, so a set edited there and
        // a set edited here are the same file.
        "faces/classic.json" to "faces/classic.json",
        "faces/bloom.json" to "faces/bloom.json",
        "faces/pixel.json" to "faces/pixel.json",
        "faces/bmo.json" to "faces/bmo.json",
        // The pet's VOICE, which is a design artefact for the same reason a
        // face is: it is what the thing is like, not how it works.
        "personas/classic.json" to "personas/classic.json",
        "personas/bmo.json" to "personas/bmo.json",
        // Both format READMEs are in the project too, and are pushed with
        // everything else. They were recorded below as "ours, no upstream"
        // until 2026-08-11, which was simply wrong — design-remote.py has been
        // fingerprinting and pushing faces/README.md the whole time. Only the
        // top-level README.md, which is about the COPY rather than copied, is
        // genuinely ours.
        "faces/README.md" to "faces/README.md",
        "personas/README.md" to "personas/README.md",
        // The design project's click-through prototype reads its face geometry
        // from this, and it is generated by tools/gen-faces.py like the C table
        // and the Kotlin. It had fallen OUT of the generator and spent a schema
        // change in the project still claiming to be generated — three sets and
        // filled-lozenge mouths against the device's four and stroked arcs.
        // Recording it here is what makes design-remote.py --check see it.
        "components/pet/faceSets.jsx" to "components/pet/faceSets.jsx",
        // Two design-system CARDS that used to be hand-drawn, and were the
        // clearest demonstration of why that fails: `brand-pet-face` still drew
        // a PORTRAIT panel and six flat-mouthed faces, and `colors-debt`
        // described two placeholder #defines that had been retired and whose
        // whole premise — that the pet has two colours — stopped being true when
        // colour became per-set. Both are generated from faces/*.json now.
        // ...and `motion` asserted a single 5400 ms blink for every state of
        // every set, months after motion became per-state. All four of these are
        // generated from faces/*.json now, so the worst they can be is a picture
        // of a set that changed — which `gen-faces.py --check` catches.
        "guidelines/brand-pet-face.html" to "guidelines/brand-pet-face.html",
        "guidelines/brand-pet-voice.html" to "guidelines/brand-pet-voice.html",
        "guidelines/colors-pet.html" to "guidelines/colors-pet.html",
        "guidelines/motion.html" to "guidelines/motion.html",
        "faces/preview/classic.card.html" to "faces/preview/classic.card.html",
        "faces/preview/bloom.card.html" to "faces/preview/bloom.card.html",
        "faces/preview/pixel.card.html" to "faces/preview/pixel.card.html",
        "faces/preview/bmo.card.html" to "faces/preview/bmo.card.html",
    )

    /** Files here that are ours and have no upstream, each with its reason. */
    private val notVendored = mapOf(
        "README.md" to "explains what this directory is; it is about the copy, not copied",
    )

    private fun dir(): File {
        var d: File? = File("").absoluteFile
        repeat(5) {
            val c = File(d, "design-system")
            if (c.isDirectory) return c
            d = d?.parentFile
        }
        throw AssertionError(
            "design-system/ not found from ${File("").absolutePath} — this test reads " +
                "the directory, so a wrong path would make it pass by finding nothing."
        )
    }

    @Test
    fun `every file in design-system is either vendored or explained`() {
        val present = dir().walkTopDown()
            .filter { it.isFile && !it.name.startsWith(".") }
            .map { it.relativeTo(dir()).path }
            .toSet()

        assertTrue("design-system/ has no files at all", present.size >= 6)

        val unaccounted = present - vendored.keys - notVendored.keys
        assertTrue(
            buildString {
                append("These files are in design-system/ with no recorded upstream:\n")
                unaccounted.sorted().forEach { append("  $it\n") }
                append("  → if it is a copy of a design-project file, add it to `vendored`\n")
                append("    and to tools/design-sync.sh so a pull refreshes it. If it is\n")
                append("    ours, add it to `notVendored` WITH A REASON.\n")
                append("  A manifest written on this side can only check the code against\n")
                append("  itself — that is the fault this test exists for.\n")
            },
            unaccounted.isEmpty(),
        )
    }

    @Test
    fun `every vendored file is actually present`() {
        val missing = vendored.keys.filter { !File(dir(), it).isFile }
        assertTrue("recorded as vendored but not on disk: $missing", missing.isEmpty())
    }

    @Test
    fun `the two manifests are named as design-project files, not repo artefacts`() {
        /*
         * The specific regression this guards: someone adds a manifest here
         * because it is convenient, the sync tests read it, and it quietly
         * becomes a second source of truth that agrees with the code by
         * construction. Both `.txt` files were exactly that until 2026-08-09.
         */
        listOf("strings.txt", "components.txt").forEach {
            assertTrue("$it is no longer recorded as vendored", it in vendored)
        }
    }
}
