package com.digitalpet.usb

/**
 * The ESP32 ROM bootloader's wire protocol, as far as identifying a chip.
 *
 * **SPIKE, and deliberately read-only.** Nothing here writes flash. It syncs
 * with the ROM loader and reads one register, which is enough to answer the
 * three questions that decide whether flashing the pet from the phone is worth
 * building: can the phone see the board, can we get it into download mode, and
 * can we talk to it once we have.
 *
 * ### Why the protocol is separated from the USB
 *
 * Everything here is bytes in, bytes out — framing, checksums, little-endian
 * fields — and every one of those is the kind of arithmetic that is wrong by
 * one and looks right. [PetUsbLink] holds the part that needs a phone and a
 * cable; this part needs neither, so it can be tested by mutation like the rest
 * of the codebase.
 *
 * **The test vectors were generated by esptool's own framing rules rather than
 * derived here**, so a mistake in this file cannot also be the thing checking
 * it. That is the same independence rule the face-set arc check came down to.
 *
 * ### The format
 *
 * Frames are SLIP: `0xC0` delimits, `0xDB` escapes (`0xDB 0xDC` for a literal
 * `0xC0`, `0xDB 0xDD` for a literal `0xDB`). Inside a frame, a command is
 *
 * ```
 * 0x00  direction (host -> chip)
 * op    1 byte
 * len   2 bytes, little endian, of the payload
 * chk   4 bytes, little endian — only meaningful for the DATA commands
 * data  len bytes
 * ```
 *
 * and a reply is the same shape with direction `0x01` and a 4-byte `value`
 * where the checksum sits. `value` is what carries a register's contents.
 */
object EspRom {

    /** `CHIP_DETECT_MAGIC_REG_ADDR`. Reads a constant identifying the silicon. */
    const val CHIP_MAGIC_ADDR = 0x40001000

    const val CMD_SYNC: Byte = 0x08
    const val CMD_READ_REG: Byte = 0x0A
    const val CMD_FLASH_BEGIN: Byte = 0x02
    const val CMD_FLASH_DATA: Byte = 0x03
    const val CMD_FLASH_END: Byte = 0x04
    const val CMD_SPI_ATTACH: Byte = 0x0D
    const val CMD_SPI_FLASH_MD5: Byte = 0x13

    /**
     * How much flash one FLASH_DATA carries. **0x400 is the ROM loader's
     * figure**; the downloadable stub raises it to 0x4000, which is most of why
     * esptool uploads a stub before writing anything. Sending more than the
     * loader in use accepts is not a slow write, it is a rejected one.
     */
    const val FLASH_BLOCK = 0x400

    /** The ROM's checksum seed for the DATA commands. */
    const val CHECKSUM_MAGIC = 0xEF

    private const val END = 0xC0.toByte()
    private const val ESC = 0xDB.toByte()
    private const val ESC_END = 0xDC.toByte()
    private const val ESC_ESC = 0xDD.toByte()

    /**
     * Chip magic → name.
     *
     * **Only the value this project has actually read from a board is here.**
     * Measured on the pet: `0x40001000` reads `0x00000009` on the ESP32-S3 it
     * runs on, confirmed against `esptool.py` on the same hardware. Adding
     * entries for chips nobody has plugged in would be transcribing a table and
     * calling it knowledge — and the failure it invites is flashing an S3 image
     * onto something else, which is exactly what the check exists to stop.
     */
    fun chipName(magic: Int): String? = when (magic) {
        0x00000009 -> "ESP32-S3"
        else -> null
    }

    /** SLIP-frame one packet, delimiters included. */
    fun slipEncode(body: ByteArray): ByteArray {
        val out = ArrayList<Byte>(body.size + 8)
        out.add(END)
        for (b in body) when (b) {
            ESC -> { out.add(ESC); out.add(ESC_ESC) }
            END -> { out.add(ESC); out.add(ESC_END) }
            else -> out.add(b)
        }
        out.add(END)
        return out.toByteArray()
    }

    /**
     * Every complete frame in [buf], unescaped.
     *
     * Returns a list because a single bulk read can carry more than one — the
     * ROM answers a sync burst with several — and drops anything not yet
     * terminated, so a partial frame at the end of a read is simply not there
     * rather than being returned half-parsed.
     */
    fun slipDecode(buf: ByteArray): List<ByteArray> {
        val frames = ArrayList<ByteArray>()
        var cur: ArrayList<Byte>? = null
        var escaped = false
        for (b in buf) {
            when {
                b == END -> {
                    // An empty frame is the gap between two delimiters, not a
                    // message: C0 C0 appears whenever frames are back to back.
                    if (cur != null && cur.isNotEmpty()) frames.add(cur.toByteArray())
                    cur = ArrayList()
                    escaped = false
                }
                cur == null -> Unit           // bytes before the first delimiter
                escaped -> {
                    cur.add(if (b == ESC_END) END else if (b == ESC_ESC) ESC else b)
                    escaped = false
                }
                b == ESC -> escaped = true
                else -> cur.add(b)
            }
        }
        return frames
    }

    /** A command, framed and ready to write. */
    fun command(op: Byte, payload: ByteArray, checksum: Int = 0): ByteArray {
        val body = ByteArray(8 + payload.size)
        body[0] = 0x00
        body[1] = op
        body[2] = (payload.size and 0xFF).toByte()
        body[3] = ((payload.size shr 8) and 0xFF).toByte()
        body[4] = (checksum and 0xFF).toByte()
        body[5] = ((checksum shr 8) and 0xFF).toByte()
        body[6] = ((checksum shr 16) and 0xFF).toByte()
        body[7] = ((checksum shr 24) and 0xFF).toByte()
        payload.copyInto(body, 8)
        return slipEncode(body)
    }

    /**
     * The sync burst: a fixed 36-byte pattern the ROM answers and nothing else
     * does. It is sent repeatedly because the chip may still be booting.
     */
    fun sync(): ByteArray =
        command(CMD_SYNC, byteArrayOf(0x07, 0x07, 0x12, 0x20) + ByteArray(32) { 0x55 })

    fun readReg(addr: Int): ByteArray = command(
        CMD_READ_REG,
        byteArrayOf(
            (addr and 0xFF).toByte(),
            ((addr shr 8) and 0xFF).toByte(),
            ((addr shr 16) and 0xFF).toByte(),
            ((addr shr 24) and 0xFF).toByte(),
        )
    )

    /**
     * The ROM's checksum: seed 0xEF, XOR every byte.
     *
     * It goes in the header's checksum field and is **only** meaningful for the
     * DATA commands. Every other command sends zero there, which is why
     * [command] defaults it.
     */
    fun checksum(data: ByteArray): Int {
        var state = CHECKSUM_MAGIC
        for (b in data) state = state xor (b.toInt() and 0xFF)
        return state
    }

    private fun le32(v: Int) = byteArrayOf(
        (v and 0xFF).toByte(),
        ((v shr 8) and 0xFF).toByte(),
        ((v shr 16) and 0xFF).toByte(),
        ((v shr 24) and 0xFF).toByte(),
    )

    /**
     * Enable the SPI flash pins. The ESP32 family needs this before any flash
     * command; the ESP8266 did it inside FLASH_BEGIN, which is why esptool
     * describes it as a quirk rather than a step.
     *
     * The ROM loader takes a second `is legacy` word the stub does not.
     */
    fun spiAttach(): ByteArray =
        command(CMD_SPI_ATTACH, le32(0) + le32(0))

    /**
     * Begin a write, and **erase** the region.
     *
     * The five words are erase size, block count, block size, offset, and an
     * encryption flag. **The fifth is present because the ESP32-S3 sets
     * `SUPPORTS_ENCRYPTED_FLASH`** — chips without it take four, and sending
     * the wrong arity is a command the ROM rejects rather than misreads.
     *
     * The erase happens up front and synchronously on the ROM loader, so the
     * reply to this can take seconds for a megabyte. That is a timeout for the
     * caller to get right, not something to make smaller here.
     */
    fun flashBegin(eraseSize: Int, offset: Int, blockSize: Int = FLASH_BLOCK): ByteArray {
        val blocks = (eraseSize + blockSize - 1) / blockSize
        return command(
            CMD_FLASH_BEGIN,
            le32(eraseSize) + le32(blocks) + le32(blockSize) + le32(offset) + le32(0),
        )
    }

    /**
     * One block. [seq] counts from zero within the current [flashBegin] and is
     * how the ROM knows where the block goes — the offset is not repeated.
     */
    fun flashData(data: ByteArray, seq: Int): ByteArray = command(
        CMD_FLASH_DATA,
        le32(data.size) + le32(seq) + le32(0) + le32(0) + data,
        checksum(data),
    )

    /**
     * Leave flash mode. The word is **inverted**: 0 reboots, 1 stays in the
     * loader. esptool writes `int(not reboot)` and the inversion is easy to
     * mirror backwards, which would leave the pet sitting in the bootloader
     * looking bricked after a successful flash.
     */
    fun flashEnd(reboot: Boolean): ByteArray =
        command(CMD_FLASH_END, le32(if (reboot) 0 else 1))

    /** MD5 of a flash region, for verifying what was written. */
    fun flashMd5(addr: Int, size: Int): ByteArray =
        command(CMD_SPI_FLASH_MD5, le32(addr) + le32(size) + le32(0) + le32(0))

    /**
     * @param data the reply's payload with the two status bytes removed. The
     *   ROM loader returns the MD5 here as 32 ASCII hex characters — already
     *   formatted, unlike the stub, which returns 16 raw bytes.
     */
    data class Reply(val op: Byte, val value: Int, val ok: Boolean, val data: ByteArray = ByteArray(0))

    /**
     * Parse one unescaped frame.
     *
     * Null for anything that is not a reply — a frame too short to hold a
     * header, or one whose direction byte is not `0x01`. The ROM echoes noise
     * during reset and a stray frame must not read as a successful answer.
     *
     * **Status is the LAST TWO BYTES, not the first two of the payload.** The
     * payload is `len` bytes and the trailing pair is `[failed, error]`; for
     * READ_REG the payload IS just that pair, which makes the two readings look
     * identical on the one command this spike sends. They are not, and a
     * flashing implementation reading the front would misjudge every write.
     */
    fun parse(frame: ByteArray): Reply? {
        if (frame.size < 8) return null
        if (frame[0] != 0x01.toByte()) return null
        val len = (frame[2].toInt() and 0xFF) or ((frame[3].toInt() and 0xFF) shl 8)
        if (frame.size < 8 + len) return null
        val value = (frame[4].toInt() and 0xFF) or
            ((frame[5].toInt() and 0xFF) shl 8) or
            ((frame[6].toInt() and 0xFF) shl 16) or
            ((frame[7].toInt() and 0xFF) shl 24)
        val failed = if (len >= 2) frame[8 + len - 2] else 1
        val data = if (len > 2) frame.copyOfRange(8, 8 + len - 2) else ByteArray(0)
        return Reply(op = frame[1], value = value, ok = failed == 0.toByte(), data = data)
    }
}
