package com.digitalpet.usb

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * **The vectors here were generated by esptool's own framing rules, not derived
 * from [EspRom].** If both sides were my arithmetic, agreeing would prove only
 * that I was consistent — the same independence problem the face-set arc check
 * turned on, where `FaceSyncTest` compared two things that were both correct
 * and both drawn from the same wrong number.
 *
 * The expected chip magic is measured rather than looked up: `esptool.py
 * read_mem 0x40001000` on the pet's own board returns `0x00000009`, and
 * `chip_id` on the same board says ESP32-S3.
 */
class EspRomTest {

    private fun hex(b: ByteArray) = b.joinToString("") { "%02x".format(it) }

    @Test
    fun `the sync burst is byte-for-byte what esptool sends`() {
        assertEquals(
            "c00008240000000000070712205555555555555555555555555555555555555555" +
                "555555555555555555555555c0",
            hex(EspRom.sync()),
        )
    }

    @Test
    fun `read_reg frames the address little-endian`() {
        // 0x40001000 goes out as 00 10 00 40. Big-endian would be a valid frame
        // addressed at 0x00100040, which reads as zero and looks like a chip
        // that answered — the worst kind of wrong.
        assertEquals("c0000a04000000000000100040c0", hex(EspRom.readReg(EspRom.CHIP_MAGIC_ADDR)))
    }

    @Test
    fun `slip escapes both special bytes and nothing else`() {
        assertEquals("c0dbdcdbdd41c0", hex(EspRom.slipEncode(byteArrayOf(0xC0.toByte(), 0xDB.toByte(), 0x41))))
    }

    @Test
    fun `decode is the inverse of encode, including the escapes`() {
        val payload = byteArrayOf(0x00, 0xC0.toByte(), 0xDB.toByte(), 0x55, 0xDB.toByte(), 0xC0.toByte())
        val frames = EspRom.slipDecode(EspRom.slipEncode(payload))
        assertEquals(1, frames.size)
        assertArrayEquals(payload, frames[0])
    }

    @Test
    fun `several frames in one read are all returned`() {
        // A single bulk transfer routinely carries more than one reply, because
        // sync is sent as a burst. Dropping the tail would look like a chip that
        // answered once and stopped.
        val two = EspRom.slipEncode(byteArrayOf(1, 2)) + EspRom.slipEncode(byteArrayOf(3, 4))
        val frames = EspRom.slipDecode(two)
        assertEquals(2, frames.size)
        assertArrayEquals(byteArrayOf(1, 2), frames[0])
        assertArrayEquals(byteArrayOf(3, 4), frames[1])
    }

    @Test
    fun `a partial frame is not returned at all`() {
        // Terminated frame, then an unterminated one. Returning the second
        // half-parsed would hand a caller a truncated reply as though complete.
        val buf = EspRom.slipEncode(byteArrayOf(1, 2)) + byteArrayOf(0xC0.toByte(), 9, 9)
        val frames = EspRom.slipDecode(buf)
        assertEquals(1, frames.size)
        assertArrayEquals(byteArrayOf(1, 2), frames[0])
    }

    @Test
    fun `a read_reg reply yields the register contents`() {
        val frame = EspRom.slipDecode(
            byteArrayOf(
                0xc0.toByte(), 0x01, 0x0a, 0x02, 0x00, 0x09, 0x00, 0x00, 0x00,
                0x00, 0x00, 0xc0.toByte(),
            )
        ).single()
        val reply = EspRom.parse(frame)!!
        assertEquals(EspRom.CMD_READ_REG, reply.op)
        assertEquals(9, reply.value)
        assertTrue(reply.ok)
        assertEquals("ESP32-S3", EspRom.chipName(reply.value))
    }

    @Test
    fun `a failed reply is not ok, and status is read from the END`() {
        /*
         * THIS TEST WAS USELESS IN ITS FIRST FORM and a mutation proved it. It
         * used a 2-byte payload, where the front of the payload and the last two
         * bytes ARE THE SAME BYTES — so reading the status from the wrong end
         * passed. My own doc comment on `parse` had said exactly that would
         * happen and I wrote the test that way anyway.
         *
         * A 4-byte payload separates them: `00 00 05 00` has a zero at the front
         * and the failure flag at the back. Reading the front calls this a
         * success.
         */
        val failedLong = byteArrayOf(
            0x01, 0x0a, 0x04, 0x00, 0x09, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x05, 0x00,
        )
        assertEquals(false, EspRom.parse(failedLong)!!.ok)

        val okLong = byteArrayOf(
            0x01, 0x0a, 0x04, 0x00, 0x09, 0x00, 0x00, 0x00,
            0x05, 0x00, 0x00, 0x00,
        )
        assertTrue("a non-zero byte at the FRONT is payload, not status", EspRom.parse(okLong)!!.ok)

        // And the short form the spike actually sends still works.
        assertEquals(
            false,
            EspRom.parse(byteArrayOf(0x01, 0x0a, 0x02, 0x00, 0x09, 0x00, 0x00, 0x00, 0x05, 0x00))!!.ok,
        )
    }

    @Test
    fun `frames that are not replies are rejected rather than guessed at`() {
        /*
         * Direction 0x00 is our own command echoed back, which happens on a
         * native-USB board because the peripheral loops back. Reading it as a
         * reply would report a chip magic of whatever the checksum field held.
         *
         * THE FRAME HAS TO BE OTHERWISE VALID or this proves nothing — the
         * first version used a sync echo whose declared length (36) exceeded
         * its size, so the LENGTH check rejected it and the direction check
         * was never reached. A mutation removing the direction check passed.
         * This one is a complete, well-formed frame in the wrong direction.
         */
        assertNull(
            EspRom.parse(byteArrayOf(0x00, 0x0a, 0x02, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00))
        )
        assertNull(EspRom.parse(byteArrayOf(0x01, 0x0a)))
        // Claims 8 bytes of payload and carries none.
        assertNull(EspRom.parse(byteArrayOf(0x01, 0x0a, 0x08, 0x00, 0, 0, 0, 0)))
    }

    // ---- the flash commands -------------------------------------------------
    //
    // Vectors below are esptool's struct layouts packed in Python, so a mistake
    // in EspRom cannot also be the thing checking it.

    @Test
    fun `spi_attach sends the ROM loader's two words`() {
        // The second word is the ROM's `is legacy` argument. The stub takes one
        // word; sending the stub's shape to the ROM is a rejected command.
        assertEquals("c0000d0800000000000000000000000000c0", hex(EspRom.spiAttach()))
    }

    @Test
    fun `flash_begin carries five words, including the encryption flag`() {
        // 22368 bytes at offset 0 in 0x400 blocks is 22 blocks. The fifth word
        // exists because the ESP32-S3 sets SUPPORTS_ENCRYPTED_FLASH — a chip
        // without it takes four, and the arity is not a detail the ROM forgives.
        assertEquals(
            "c000021400000000006057000016000000000400000000000000000000c0",
            hex(EspRom.flashBegin(eraseSize = 22368, offset = 0)),
        )
    }

    @Test
    fun `flash_begin rounds the block count up`() {
        // One byte past a block boundary still needs a whole extra block. A
        // truncating division silently drops the tail of every image whose size
        // is not a multiple of 1024 — which is most of them.
        val oneOver = EspRom.flashBegin(eraseSize = 0x401, offset = 0)
        // blocks is the second word of the payload: bytes 8..11 of the frame
        // (1 delimiter + 8 header) — 2 here, not 1.
        assertEquals(2, oneOver[9 + 4].toInt())
    }

    @Test
    fun `flash_data carries the checksum in the header, not the payload`() {
        assertEquals(
            "c000031300ef00000003000000070000000000000000000000010203c0",
            hex(EspRom.flashData(byteArrayOf(1, 2, 3), seq = 7)),
        )
    }

    @Test
    fun `the checksum is seeded, so an empty block is not zero`() {
        // Seed 0xEF XOR nothing is 0xEF. A zero-seeded checksum would be
        // accepted for some blocks and rejected for others, which reads as
        // flaky hardware rather than as a wrong constant.
        assertEquals(0xEF, EspRom.checksum(ByteArray(0)))
        assertEquals(0xEF, EspRom.checksum(byteArrayOf(1, 2, 3)))
        assertEquals(0xEE, EspRom.checksum(byteArrayOf(1)))
    }

    @Test
    fun `flash_end inverts the reboot flag`() {
        // 0 reboots, 1 stays in the loader. Mirroring this backwards leaves the
        // pet sitting in the bootloader, looking bricked after a good flash.
        assertEquals("c0000404000000000000000000c0", hex(EspRom.flashEnd(reboot = true)))
        assertEquals("c0000404000000000001000000c0", hex(EspRom.flashEnd(reboot = false)))
    }

    @Test
    fun `md5 asks for a region`() {
        assertEquals(
            "c000131000000000000000020070fa11000000000000000000c0",
            hex(EspRom.flashMd5(0x20000, 1178224)),
        )
    }

    @Test
    fun `a reply's payload is returned without the status bytes`() {
        // The ROM answers MD5 with 32 ASCII hex characters FOLLOWED by the two
        // status bytes. Handing the caller the status as part of the digest
        // would produce a hash that never matches and no clue why.
        val digest = "d41d8cd98f00b204e9800998ecf8427e"
        val payload = digest.toByteArray() + byteArrayOf(0, 0)
        val frame = byteArrayOf(0x01, 0x13, payload.size.toByte(), 0x00, 0, 0, 0, 0) + payload
        val reply = EspRom.parse(frame)!!
        assertTrue(reply.ok)
        assertEquals(digest, String(reply.data))
    }

    @Test
    fun `an unknown magic is null rather than a plausible guess`() {
        // The whole point of the check: refuse to flash something that is not
        // the chip this firmware was built for.
        assertNull(EspRom.chipName(0x00f01d83))   // ESP32
        assertNull(EspRom.chipName(0))
    }
}
