/* GENERATED by tools/gen-faces.py from design-system/faces/. DO NOT EDIT.
   The design project's path for this file is components/pet/faceSets.jsx.

   DATA ONLY — PetPanel.jsx draws it, and is hand-written. Same split as the
   app: PetFaceSets.kt is generated, the Compose panel that reads it is not.

   Sizes are DEVICE PIXELS on the pet's 448x368 screen. That screen is
   LANDSCAPE: the panel is wired portrait and the firmware rotates it 270
   degrees (PET_ROTATION_DEG in pet-esp32.c), so landscape is what anyone ever
   sees. `cx` / `cy` are centres relative to the middle of the panel.

   Every stroke is pre-resolved. `kind` is one of:
     "none"  nothing to draw — the dead face has no mouth
     "bar"   a filled lozenge `w` x `thick`, corner radius `radius`
     "arc"   a stroke `thick` wide along a circle of radius `r`, whose centre
             sits `dy` from the shape's own centre, swept from `start` to `end`
             degrees (0 at 3 o'clock, clockwise, y down) with SVG sweep flag
             `sweep`. `round` is the line cap.
     "spiral" a stroke `thick` wide along the path `d`, inside a square of side
             `box` centred on the eye, TURNING once every `spinMs`. Only the
             sick face wears it. The spin is not decoration: a spiral that has
             stopped reads as a pattern rather than as a symptom, so a
             prototype that drew this still would be drawing a different face.
   The trig that produced `r` / `dy` / `start` / `end` lives in gen-faces.py and
   is done ONCE, for all four renderers — see arc_of(). A renderer that
   re-derived it would be a fourth chance to draw the smile slightly wrong.

   `motion` is null for a state that does not move, which is how `dead` says it
   is dead. Otherwise blinkMs 0 means "this state does not blink". */
export const PET_SCREEN = { width: 448, height: 368 };

export const FACE_SETS = {
  "classic": {
    "id": "classic",
    "name": "Classic",
    "description": "The face the pet has always worn. Gold on black, pill eyes. Its geometry is the firmware's own apply_mood() as it stood at protocol v8, with one deliberate change: happy now curves up and sad curves down, because a face set has to mean what it says.",
    "persona": "classic",
    "colors": {
      "eye": "#F5A623",
      "mouth": "#F5A623",
      "panel": "#000000",
      "control": "#14202A",
      "text": "#E8E6F0"
    },
    "stageScale": {
      "egg": 55,
      "child": 70,
      "teen": 85,
      "adult": 100
    },
    "faces": {
      "neutral": {
        "eyes": [
          {
            "kind": "bar",
            "w": 74,
            "thick": 96,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -56
          },
          {
            "kind": "bar",
            "w": 74,
            "thick": 96,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -56
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 120,
          "thick": 16,
          "round": true,
          "radius": 8.0,
          "cy": 40
        },
        "motion": {
          "blinkMs": 5400,
          "shutMs": 300,
          "breatheMs": 1900,
          "breatheFrom": -4,
          "breatheTo": 6,
          "spinMs": 0
        }
      },
      "happy": {
        "eyes": [
          {
            "kind": "arc",
            "w": 74,
            "thick": 14,
            "round": true,
            "r": 51,
            "dy": 35,
            "start": 223,
            "end": 317,
            "sweep": 1,
            "cx": -64,
            "cy": -59
          },
          {
            "kind": "arc",
            "w": 74,
            "thick": 14,
            "round": true,
            "r": 51,
            "dy": 35,
            "start": 223,
            "end": 317,
            "sweep": 1,
            "cx": 64,
            "cy": -59
          }
        ],
        "mouth": {
          "kind": "arc",
          "w": 150,
          "thick": 22,
          "round": true,
          "r": 151,
          "dy": -131,
          "start": 60,
          "end": 120,
          "sweep": 0,
          "cy": 40
        },
        "motion": {
          "blinkMs": 6200,
          "shutMs": 300,
          "breatheMs": 2300,
          "breatheFrom": -5,
          "breatheTo": 8,
          "spinMs": 0
        }
      },
      "sleepy": {
        "eyes": [
          {
            "kind": "bar",
            "w": 74,
            "thick": 16,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -51
          },
          {
            "kind": "bar",
            "w": 74,
            "thick": 16,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -51
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 56,
          "thick": 10,
          "round": true,
          "radius": 5.0,
          "cy": 40
        },
        "motion": {
          "blinkMs": 9000,
          "shutMs": 300,
          "breatheMs": 3200,
          "breatheFrom": -3,
          "breatheTo": 5,
          "spinMs": 0
        }
      },
      "surprised": {
        "eyes": [
          {
            "kind": "bar",
            "w": 88,
            "thick": 112,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -58
          },
          {
            "kind": "bar",
            "w": 88,
            "thick": 112,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -58
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 52,
          "thick": 52,
          "round": true,
          "radius": 26.0,
          "cy": 40
        },
        "motion": {
          "blinkMs": 8000,
          "shutMs": 300,
          "breatheMs": 1200,
          "breatheFrom": -1,
          "breatheTo": 2,
          "spinMs": 0
        }
      },
      "sad": {
        "eyes": [
          {
            "kind": "bar",
            "w": 74,
            "thick": 62,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -49
          },
          {
            "kind": "bar",
            "w": 74,
            "thick": 62,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -49
          }
        ],
        "mouth": {
          "kind": "arc",
          "w": 80,
          "thick": 12,
          "round": true,
          "r": 104,
          "dy": 96,
          "start": 247,
          "end": 293,
          "sweep": 1,
          "cy": 40
        },
        "motion": {
          "blinkMs": 7000,
          "shutMs": 300,
          "breatheMs": 2600,
          "breatheFrom": -3,
          "breatheTo": 4,
          "spinMs": 0
        }
      },
      "sick": {
        "eyes": [
          {
            "kind": "spiral",
            "thick": 10,
            "turns": 2,
            "spinMs": 2600,
            "d": "M0.00,0.00 L0.76,0.19 L1.37,0.80 L1.67,1.67 L1.60,2.74 L1.03,3.84 L0.00,4.75 L-1.44,5.36 L-3.15,5.47 L-5.05,5.05 L-6.84,3.95 L-8.40,2.24 L-9.50,0.00 L-9.96,-2.66 L-9.61,-5.55 L-8.40,-8.40 L-6.35,-10.98 L-3.50,-13.00 L0.00,-14.25 L3.88,-14.52 L7.90,-13.72 L11.74,-11.74 L15.09,-8.70 L17.59,-4.71 L19.00,0.00 L19.11,5.13 L17.82,10.30 L15.12,15.12 L11.10,19.19 L5.93,22.19 L0.00,23.75 L-6.35,23.71 L-12.65,21.93 L-18.47,18.47 L-23.29,13.45 L-26.75,7.18 L-28.50,0.00 L-28.31,-7.60 L-26.07,-15.05 L-21.85,-21.85 L-15.85,-27.44 L-8.40,-31.35 L0.00,-33.25 L8.82,-32.87 L17.40,-30.17 L25.19,-25.19 L31.54,-18.20 L35.95,-9.61 L38.00,0.00",
            "box": 86.0,
            "cx": -64,
            "cy": -52
          },
          {
            "kind": "spiral",
            "thick": 11,
            "turns": 2,
            "spinMs": 2600,
            "d": "M0.00,0.00 L-0.72,0.18 L-1.30,0.76 L-1.58,1.58 L-1.51,2.59 L-0.97,3.64 L0.00,4.50 L1.37,5.08 L2.99,5.18 L4.79,4.79 L6.48,3.74 L7.96,2.12 L9.00,0.00 L9.43,-2.52 L9.11,-5.26 L7.96,-7.96 L6.01,-10.40 L3.31,-12.31 L0.00,-13.50 L-3.67,-13.75 L-7.49,-13.00 L-11.12,-11.12 L-14.29,-8.24 L-16.67,-4.46 L-18.00,0.00 L-18.11,4.86 L-16.88,9.76 L-14.33,14.33 L-10.51,18.18 L-5.62,21.02 L0.00,22.50 L6.01,22.46 L11.99,20.77 L17.50,17.50 L22.07,12.74 L25.34,6.80 L27.00,0.00 L26.82,-7.20 L24.70,-14.26 L20.70,-20.70 L15.01,-25.99 L7.96,-29.70 L0.00,-31.50 L-8.35,-31.14 L-16.49,-28.58 L-23.87,-23.87 L-29.88,-17.24 L-34.06,-9.11 L-36.00,0.00",
            "box": 83.0,
            "cx": 64,
            "cy": -52
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 40,
          "thick": 40,
          "round": true,
          "radius": 20.0,
          "cy": 40
        },
        "motion": {
          "blinkMs": 3200,
          "shutMs": 300,
          "breatheMs": 900,
          "breatheFrom": -2,
          "breatheTo": 3,
          "spinMs": 2600
        }
      },
      "dead": {
        "eyes": [
          {
            "kind": "bar",
            "w": 74,
            "thick": 8,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -56
          },
          {
            "kind": "bar",
            "w": 74,
            "thick": 8,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -56
          }
        ],
        "mouth": {
          "kind": "none",
          "cy": 40
        },
        "motion": null
      },
      "asleep": {
        "eyes": [
          {
            "kind": "bar",
            "w": 74,
            "thick": 8,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -56
          },
          {
            "kind": "bar",
            "w": 74,
            "thick": 8,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -56
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 56,
          "thick": 10,
          "round": true,
          "radius": 5.0,
          "cy": 40
        },
        "motion": {
          "blinkMs": 0,
          "shutMs": 300,
          "breatheMs": 3600,
          "breatheFrom": -2,
          "breatheTo": 4,
          "spinMs": 0
        }
      }
    }
  },
  "bloom": {
    "id": "bloom",
    "name": "Bloom",
    "description": "Wide, soft and close-set \u2014 a gentler pet. Everything is rounded to the limit and the eyes sit nearer together and lower, which reads as younger without touching the stage scales.",
    "persona": "classic",
    "colors": {
      "eye": "#FF8FA3",
      "mouth": "#FFC2CD",
      "panel": "#140A0F",
      "control": "#2A1A20",
      "text": "#FFE4EA"
    },
    "stageScale": {
      "egg": 55,
      "child": 70,
      "teen": 85,
      "adult": 100
    },
    "faces": {
      "neutral": {
        "eyes": [
          {
            "kind": "bar",
            "w": 84,
            "thick": 88,
            "round": true,
            "radius": 999,
            "cx": -56,
            "cy": -44
          },
          {
            "kind": "bar",
            "w": 84,
            "thick": 88,
            "round": true,
            "radius": 999,
            "cx": 56,
            "cy": -44
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 104,
          "thick": 20,
          "round": true,
          "radius": 10.0,
          "cy": 48
        },
        "motion": {
          "blinkMs": 5400,
          "shutMs": 300,
          "breatheMs": 1900,
          "breatheFrom": -4,
          "breatheTo": 6,
          "spinMs": 0
        }
      },
      "happy": {
        "eyes": [
          {
            "kind": "arc",
            "w": 84,
            "thick": 16,
            "round": true,
            "r": 58,
            "dy": 40,
            "start": 224,
            "end": 316,
            "sweep": 1,
            "cx": -56,
            "cy": -47
          },
          {
            "kind": "arc",
            "w": 84,
            "thick": 16,
            "round": true,
            "r": 58,
            "dy": 40,
            "start": 224,
            "end": 316,
            "sweep": 1,
            "cx": 56,
            "cy": -47
          }
        ],
        "mouth": {
          "kind": "arc",
          "w": 156,
          "thick": 20,
          "round": true,
          "r": 130,
          "dy": -104,
          "start": 53,
          "end": 127,
          "sweep": 0,
          "cy": 48
        },
        "motion": {
          "blinkMs": 6200,
          "shutMs": 300,
          "breatheMs": 2300,
          "breatheFrom": -5,
          "breatheTo": 8,
          "spinMs": 0
        }
      },
      "sleepy": {
        "eyes": [
          {
            "kind": "bar",
            "w": 84,
            "thick": 18,
            "round": true,
            "radius": 999,
            "cx": -56,
            "cy": -39
          },
          {
            "kind": "bar",
            "w": 84,
            "thick": 18,
            "round": true,
            "radius": 999,
            "cx": 56,
            "cy": -39
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 60,
          "thick": 14,
          "round": true,
          "radius": 7.0,
          "cy": 48
        },
        "motion": {
          "blinkMs": 9000,
          "shutMs": 300,
          "breatheMs": 3200,
          "breatheFrom": -3,
          "breatheTo": 5,
          "spinMs": 0
        }
      },
      "surprised": {
        "eyes": [
          {
            "kind": "bar",
            "w": 96,
            "thick": 116,
            "round": true,
            "radius": 999,
            "cx": -56,
            "cy": -46
          },
          {
            "kind": "bar",
            "w": 96,
            "thick": 116,
            "round": true,
            "radius": 999,
            "cx": 56,
            "cy": -46
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 56,
          "thick": 56,
          "round": true,
          "radius": 28.0,
          "cy": 48
        },
        "motion": {
          "blinkMs": 8000,
          "shutMs": 300,
          "breatheMs": 1200,
          "breatheFrom": -1,
          "breatheTo": 2,
          "spinMs": 0
        }
      },
      "sad": {
        "eyes": [
          {
            "kind": "bar",
            "w": 84,
            "thick": 66,
            "round": true,
            "radius": 999,
            "cx": -56,
            "cy": -37
          },
          {
            "kind": "bar",
            "w": 84,
            "thick": 66,
            "round": true,
            "radius": 999,
            "cx": 56,
            "cy": -37
          }
        ],
        "mouth": {
          "kind": "arc",
          "w": 80,
          "thick": 16,
          "round": true,
          "r": 85,
          "dy": 75,
          "start": 242,
          "end": 298,
          "sweep": 1,
          "cy": 48
        },
        "motion": {
          "blinkMs": 7000,
          "shutMs": 300,
          "breatheMs": 2600,
          "breatheFrom": -3,
          "breatheTo": 4,
          "spinMs": 0
        }
      },
      "sick": {
        "eyes": [
          {
            "kind": "spiral",
            "thick": 12,
            "turns": 2,
            "spinMs": 2600,
            "d": "M0.00,0.00 L0.80,0.20 L1.44,0.84 L1.76,1.76 L1.68,2.88 L1.08,4.04 L0.00,5.00 L-1.52,5.64 L-3.32,5.76 L-5.32,5.32 L-7.20,4.16 L-8.84,2.36 L-10.00,0.00 L-10.48,-2.80 L-10.12,-5.84 L-8.84,-8.84 L-6.68,-11.56 L-3.68,-13.68 L0.00,-15.00 L4.08,-15.28 L8.32,-14.44 L12.36,-12.36 L15.88,-9.16 L18.52,-4.96 L20.00,0.00 L20.12,5.40 L18.76,10.84 L15.92,15.92 L11.68,20.20 L6.24,23.36 L0.00,25.00 L-6.68,24.96 L-13.32,23.08 L-19.44,19.44 L-24.52,14.16 L-28.16,7.56 L-30.00,0.00 L-29.80,-8.00 L-27.44,-15.84 L-23.00,-23.00 L-16.68,-28.88 L-8.84,-33.00 L0.00,-35.00 L9.28,-34.60 L18.32,-31.76 L26.52,-26.52 L33.20,-19.16 L37.84,-10.12 L40.00,0.00",
            "box": 92.0,
            "cx": -56,
            "cy": -40
          },
          {
            "kind": "spiral",
            "thick": 11,
            "turns": 2,
            "spinMs": 2600,
            "d": "M0.00,0.00 L-0.74,0.18 L-1.33,0.78 L-1.63,1.63 L-1.55,2.66 L-1.00,3.74 L0.00,4.62 L1.41,5.22 L3.07,5.33 L4.92,4.92 L6.66,3.85 L8.18,2.18 L9.25,0.00 L9.69,-2.59 L9.36,-5.40 L8.18,-8.18 L6.18,-10.69 L3.40,-12.65 L0.00,-13.88 L-3.77,-14.13 L-7.70,-13.36 L-11.43,-11.43 L-14.69,-8.47 L-17.13,-4.59 L-18.50,0.00 L-18.61,5.00 L-17.35,10.03 L-14.73,14.73 L-10.80,18.68 L-5.77,21.61 L0.00,23.12 L6.18,23.09 L12.32,21.35 L17.98,17.98 L22.68,13.10 L26.05,6.99 L27.75,0.00 L27.57,-7.40 L25.38,-14.65 L21.27,-21.27 L15.43,-26.71 L8.18,-30.52 L0.00,-32.38 L-8.58,-32.01 L-16.95,-29.38 L-24.53,-24.53 L-30.71,-17.72 L-35.00,-9.36 L-37.00,0.00",
            "box": 85.0,
            "cx": 56,
            "cy": -40
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 44,
          "thick": 44,
          "round": true,
          "radius": 22.0,
          "cy": 48
        },
        "motion": {
          "blinkMs": 3200,
          "shutMs": 300,
          "breatheMs": 900,
          "breatheFrom": -2,
          "breatheTo": 3,
          "spinMs": 2600
        }
      },
      "dead": {
        "eyes": [
          {
            "kind": "bar",
            "w": 84,
            "thick": 10,
            "round": true,
            "radius": 999,
            "cx": -56,
            "cy": -44
          },
          {
            "kind": "bar",
            "w": 84,
            "thick": 10,
            "round": true,
            "radius": 999,
            "cx": 56,
            "cy": -44
          }
        ],
        "mouth": {
          "kind": "none",
          "cy": 48
        },
        "motion": null
      },
      "asleep": {
        "eyes": [
          {
            "kind": "bar",
            "w": 84,
            "thick": 10,
            "round": true,
            "radius": 999,
            "cx": -56,
            "cy": -44
          },
          {
            "kind": "bar",
            "w": 84,
            "thick": 10,
            "round": true,
            "radius": 999,
            "cx": 56,
            "cy": -44
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 60,
          "thick": 14,
          "round": true,
          "radius": 7.0,
          "cy": 48
        },
        "motion": {
          "blinkMs": 0,
          "shutMs": 300,
          "breatheMs": 3600,
          "breatheFrom": -2,
          "breatheTo": 4,
          "spinMs": 0
        }
      }
    }
  },
  "bmo": {
    "id": "bmo",
    "name": "Little Computer",
    "description": "A tribute to the small game-console character from Adventure Time: dark features on a pale mint screen, round wide-set eyes and a tiny mouth. The one set that inverts the palette \u2014 everything else is light on black, and this is black on light, which is the whole reason it reads as a different machine rather than a recolour.",
    "persona": "bmo",
    "colors": {
      "eye": "#14332B",
      "mouth": "#14332B",
      "panel": "#AEDCC8",
      "control": "#E8F5EE",
      "text": "#14332B"
    },
    "stageScale": {
      "egg": 55,
      "child": 70,
      "teen": 85,
      "adult": 100
    },
    "faces": {
      "neutral": {
        "eyes": [
          {
            "kind": "bar",
            "w": 38,
            "thick": 38,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -34
          },
          {
            "kind": "bar",
            "w": 38,
            "thick": 38,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -34
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 44,
          "thick": 10,
          "round": true,
          "radius": 5.0,
          "cy": 46
        },
        "motion": {
          "blinkMs": 4200,
          "shutMs": 260,
          "breatheMs": 1700,
          "breatheFrom": -3,
          "breatheTo": 5,
          "spinMs": 0
        }
      },
      "happy": {
        "eyes": [
          {
            "kind": "arc",
            "w": 38,
            "thick": 9,
            "round": true,
            "r": 23,
            "dy": 13,
            "start": 214,
            "end": 326,
            "sweep": 1,
            "cx": -64,
            "cy": -37
          },
          {
            "kind": "arc",
            "w": 38,
            "thick": 9,
            "round": true,
            "r": 23,
            "dy": 13,
            "start": 214,
            "end": 326,
            "sweep": 1,
            "cx": 64,
            "cy": -37
          }
        ],
        "mouth": {
          "kind": "arc",
          "w": 74,
          "thick": 10,
          "round": true,
          "r": 51,
          "dy": -35,
          "start": 43,
          "end": 137,
          "sweep": 0,
          "cy": 46
        },
        "motion": {
          "blinkMs": 5200,
          "shutMs": 260,
          "breatheMs": 2000,
          "breatheFrom": -4,
          "breatheTo": 7,
          "spinMs": 0
        }
      },
      "sleepy": {
        "eyes": [
          {
            "kind": "bar",
            "w": 38,
            "thick": 10,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -29
          },
          {
            "kind": "bar",
            "w": 38,
            "thick": 10,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -29
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 30,
          "thick": 8,
          "round": true,
          "radius": 4.0,
          "cy": 46
        },
        "motion": {
          "blinkMs": 8000,
          "shutMs": 260,
          "breatheMs": 3000,
          "breatheFrom": -2,
          "breatheTo": 4,
          "spinMs": 0
        }
      },
      "surprised": {
        "eyes": [
          {
            "kind": "bar",
            "w": 48,
            "thick": 54,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -36
          },
          {
            "kind": "bar",
            "w": 48,
            "thick": 54,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -36
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 34,
          "thick": 34,
          "round": true,
          "radius": 17.0,
          "cy": 46
        },
        "motion": {
          "blinkMs": 7000,
          "shutMs": 260,
          "breatheMs": 1100,
          "breatheFrom": -1,
          "breatheTo": 2,
          "spinMs": 0
        }
      },
      "sad": {
        "eyes": [
          {
            "kind": "bar",
            "w": 38,
            "thick": 28,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -27
          },
          {
            "kind": "bar",
            "w": 38,
            "thick": 28,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -27
          }
        ],
        "mouth": {
          "kind": "arc",
          "w": 48,
          "thick": 10,
          "round": true,
          "r": 36,
          "dy": 28,
          "start": 229,
          "end": 311,
          "sweep": 1,
          "cy": 46
        },
        "motion": {
          "blinkMs": 6400,
          "shutMs": 260,
          "breatheMs": 2400,
          "breatheFrom": -2,
          "breatheTo": 4,
          "spinMs": 0
        }
      },
      "sick": {
        "eyes": [
          {
            "kind": "spiral",
            "thick": 8,
            "turns": 2,
            "spinMs": 2400,
            "d": "M0.00,0.00 L0.50,0.12 L0.90,0.53 L1.10,1.10 L1.05,1.80 L0.68,2.52 L0.00,3.12 L-0.95,3.52 L-2.08,3.60 L-3.33,3.33 L-4.50,2.60 L-5.53,1.48 L-6.25,0.00 L-6.55,-1.75 L-6.33,-3.65 L-5.53,-5.53 L-4.17,-7.22 L-2.30,-8.55 L0.00,-9.38 L2.55,-9.55 L5.20,-9.03 L7.72,-7.72 L9.93,-5.72 L11.57,-3.10 L12.50,0.00 L12.57,3.38 L11.72,6.78 L9.95,9.95 L7.30,12.62 L3.90,14.60 L0.00,15.62 L-4.17,15.60 L-8.32,14.43 L-12.15,12.15 L-15.32,8.85 L-17.60,4.72 L-18.75,0.00 L-18.62,-5.00 L-17.15,-9.90 L-14.38,-14.38 L-10.43,-18.05 L-5.53,-20.62 L0.00,-21.88 L5.80,-21.62 L11.45,-19.85 L16.57,-16.57 L20.75,-11.97 L23.65,-6.33 L25.00,0.00",
            "box": 58.0,
            "cx": -64,
            "cy": -30
          },
          {
            "kind": "spiral",
            "thick": 7,
            "turns": 2,
            "spinMs": 2400,
            "d": "M0.00,0.00 L-0.44,0.11 L-0.79,0.46 L-0.97,0.97 L-0.92,1.58 L-0.59,2.22 L0.00,2.75 L0.84,3.10 L1.83,3.17 L2.93,2.93 L3.96,2.29 L4.86,1.30 L5.50,0.00 L5.76,-1.54 L5.57,-3.21 L4.86,-4.86 L3.67,-6.36 L2.02,-7.52 L0.00,-8.25 L-2.24,-8.40 L-4.58,-7.94 L-6.80,-6.80 L-8.73,-5.04 L-10.19,-2.73 L-11.00,0.00 L-11.07,2.97 L-10.32,5.96 L-8.76,8.76 L-6.42,11.11 L-3.43,12.85 L0.00,13.75 L3.67,13.73 L7.33,12.69 L10.69,10.69 L13.49,7.79 L15.49,4.16 L16.50,0.00 L16.39,-4.40 L15.09,-8.71 L12.65,-12.65 L9.17,-15.88 L4.86,-18.15 L0.00,-19.25 L-5.10,-19.03 L-10.08,-17.47 L-14.59,-14.59 L-18.26,-10.54 L-20.81,-5.57 L-22.00,0.00",
            "box": 51.0,
            "cx": 64,
            "cy": -30
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 30,
          "thick": 30,
          "round": true,
          "radius": 15.0,
          "cy": 46
        },
        "motion": {
          "blinkMs": 2800,
          "shutMs": 260,
          "breatheMs": 850,
          "breatheFrom": -1,
          "breatheTo": 2,
          "spinMs": 2400
        }
      },
      "dead": {
        "eyes": [
          {
            "kind": "bar",
            "w": 38,
            "thick": 6,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -34
          },
          {
            "kind": "bar",
            "w": 38,
            "thick": 6,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -34
          }
        ],
        "mouth": {
          "kind": "none",
          "cy": 46
        },
        "motion": null
      },
      "asleep": {
        "eyes": [
          {
            "kind": "bar",
            "w": 38,
            "thick": 7,
            "round": true,
            "radius": 999,
            "cx": -64,
            "cy": -34
          },
          {
            "kind": "bar",
            "w": 38,
            "thick": 7,
            "round": true,
            "radius": 999,
            "cx": 64,
            "cy": -34
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 30,
          "thick": 8,
          "round": true,
          "radius": 4.0,
          "cy": 46
        },
        "motion": {
          "blinkMs": 0,
          "shutMs": 260,
          "breatheMs": 3400,
          "breatheFrom": -2,
          "breatheTo": 4,
          "spinMs": 0
        }
      }
    }
  },
  "pixel": {
    "id": "pixel",
    "name": "Pixel",
    "description": "Square eyes and a blocky mouth \u2014 the pet as a handheld from 1998. Proves the shape lever: nothing here changes except eyeRadius, the mouth radii and the palette, and the pet reads as a different device.",
    "persona": "classic",
    "colors": {
      "eye": "#9BE564",
      "mouth": "#9BE564",
      "panel": "#0B1400",
      "control": "#16240A",
      "text": "#D6F5B8"
    },
    "stageScale": {
      "egg": 55,
      "child": 70,
      "teen": 85,
      "adult": 100
    },
    "faces": {
      "neutral": {
        "eyes": [
          {
            "kind": "bar",
            "w": 60,
            "thick": 84,
            "round": false,
            "radius": 0,
            "cx": -62,
            "cy": -52
          },
          {
            "kind": "bar",
            "w": 60,
            "thick": 84,
            "round": false,
            "radius": 0,
            "cx": 62,
            "cy": -52
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 112,
          "thick": 16,
          "round": false,
          "radius": 0,
          "cy": 44
        },
        "motion": {
          "blinkMs": 5400,
          "shutMs": 300,
          "breatheMs": 1900,
          "breatheFrom": -4,
          "breatheTo": 6,
          "spinMs": 0
        }
      },
      "happy": {
        "eyes": [
          {
            "kind": "arc",
            "w": 60,
            "thick": 12,
            "round": false,
            "r": 39,
            "dy": 25,
            "start": 220,
            "end": 320,
            "sweep": 1,
            "cx": -62,
            "cy": -55
          },
          {
            "kind": "arc",
            "w": 60,
            "thick": 12,
            "round": false,
            "r": 39,
            "dy": 25,
            "start": 220,
            "end": 320,
            "sweep": 1,
            "cx": 62,
            "cy": -55
          }
        ],
        "mouth": {
          "kind": "arc",
          "w": 144,
          "thick": 16,
          "round": false,
          "r": 140,
          "dy": -120,
          "start": 59,
          "end": 121,
          "sweep": 0,
          "cy": 44
        },
        "motion": {
          "blinkMs": 4000,
          "shutMs": 300,
          "breatheMs": 1400,
          "breatheFrom": -4,
          "breatheTo": 6,
          "spinMs": 0
        }
      },
      "sleepy": {
        "eyes": [
          {
            "kind": "bar",
            "w": 60,
            "thick": 14,
            "round": false,
            "radius": 0,
            "cx": -62,
            "cy": -47
          },
          {
            "kind": "bar",
            "w": 60,
            "thick": 14,
            "round": false,
            "radius": 0,
            "cx": 62,
            "cy": -47
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 52,
          "thick": 10,
          "round": false,
          "radius": 0,
          "cy": 44
        },
        "motion": {
          "blinkMs": 9000,
          "shutMs": 300,
          "breatheMs": 3200,
          "breatheFrom": -3,
          "breatheTo": 5,
          "spinMs": 0
        }
      },
      "surprised": {
        "eyes": [
          {
            "kind": "bar",
            "w": 76,
            "thick": 104,
            "round": false,
            "radius": 0,
            "cx": -62,
            "cy": -54
          },
          {
            "kind": "bar",
            "w": 76,
            "thick": 104,
            "round": false,
            "radius": 0,
            "cx": 62,
            "cy": -54
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 48,
          "thick": 48,
          "round": false,
          "radius": 0,
          "cy": 44
        },
        "motion": {
          "blinkMs": 8000,
          "shutMs": 300,
          "breatheMs": 1200,
          "breatheFrom": -1,
          "breatheTo": 2,
          "spinMs": 0
        }
      },
      "sad": {
        "eyes": [
          {
            "kind": "bar",
            "w": 60,
            "thick": 56,
            "round": false,
            "radius": 0,
            "cx": -62,
            "cy": -45
          },
          {
            "kind": "bar",
            "w": 60,
            "thick": 56,
            "round": false,
            "radius": 0,
            "cx": 62,
            "cy": -45
          }
        ],
        "mouth": {
          "kind": "arc",
          "w": 68,
          "thick": 12,
          "round": false,
          "r": 76,
          "dy": 68,
          "start": 244,
          "end": 296,
          "sweep": 1,
          "cy": 44
        },
        "motion": {
          "blinkMs": 7000,
          "shutMs": 300,
          "breatheMs": 2600,
          "breatheFrom": -3,
          "breatheTo": 4,
          "spinMs": 0
        }
      },
      "sick": {
        "eyes": [
          {
            "kind": "spiral",
            "thick": 10,
            "turns": 2,
            "spinMs": 2800,
            "d": "M0.00,0.00 L0.64,0.16 L1.15,0.67 L1.41,1.41 L1.34,2.30 L0.86,3.23 L0.00,4.00 L-1.22,4.51 L-2.66,4.61 L-4.26,4.26 L-5.76,3.33 L-7.07,1.89 L-8.00,0.00 L-8.38,-2.24 L-8.10,-4.67 L-7.07,-7.07 L-5.34,-9.25 L-2.94,-10.94 L0.00,-12.00 L3.26,-12.22 L6.66,-11.55 L9.89,-9.89 L12.70,-7.33 L14.82,-3.97 L16.00,0.00 L16.10,4.32 L15.01,8.67 L12.74,12.74 L9.34,16.16 L4.99,18.69 L0.00,20.00 L-5.34,19.97 L-10.66,18.46 L-15.55,15.55 L-19.62,11.33 L-22.53,6.05 L-24.00,0.00 L-23.84,-6.40 L-21.95,-12.67 L-18.40,-18.40 L-13.34,-23.10 L-7.07,-26.40 L0.00,-28.00 L7.42,-27.68 L14.66,-25.41 L21.22,-21.22 L26.56,-15.33 L30.27,-8.10 L32.00,0.00",
            "box": 74.0,
            "cx": -62,
            "cy": -48
          },
          {
            "kind": "spiral",
            "thick": 9,
            "turns": 2,
            "spinMs": 2800,
            "d": "M0.00,0.00 L-0.58,0.14 L-1.04,0.61 L-1.28,1.28 L-1.22,2.09 L-0.78,2.93 L0.00,3.62 L1.10,4.09 L2.41,4.18 L3.86,3.86 L5.22,3.02 L6.41,1.71 L7.25,0.00 L7.60,-2.03 L7.34,-4.23 L6.41,-6.41 L4.84,-8.38 L2.67,-9.92 L0.00,-10.88 L-2.96,-11.08 L-6.03,-10.47 L-8.96,-8.96 L-11.51,-6.64 L-13.43,-3.60 L-14.50,0.00 L-14.59,3.92 L-13.60,7.86 L-11.54,11.54 L-8.47,14.64 L-4.52,16.94 L0.00,18.12 L4.84,18.10 L9.66,16.73 L14.09,14.09 L17.78,10.27 L20.42,5.48 L21.75,0.00 L21.61,-5.80 L19.89,-11.48 L16.68,-16.68 L12.09,-20.94 L6.41,-23.93 L0.00,-25.38 L-6.73,-25.09 L-13.28,-23.03 L-19.23,-19.23 L-24.07,-13.89 L-27.43,-7.34 L-29.00,0.00",
            "box": 67.0,
            "cx": 62,
            "cy": -48
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 36,
          "thick": 36,
          "round": true,
          "radius": 18.0,
          "cy": 44
        },
        "motion": {
          "blinkMs": 3200,
          "shutMs": 300,
          "breatheMs": 900,
          "breatheFrom": -2,
          "breatheTo": 3,
          "spinMs": 2800
        }
      },
      "dead": {
        "eyes": [
          {
            "kind": "bar",
            "w": 60,
            "thick": 8,
            "round": false,
            "radius": 0,
            "cx": -62,
            "cy": -52
          },
          {
            "kind": "bar",
            "w": 60,
            "thick": 8,
            "round": false,
            "radius": 0,
            "cx": 62,
            "cy": -52
          }
        ],
        "mouth": {
          "kind": "none",
          "cy": 44
        },
        "motion": null
      },
      "asleep": {
        "eyes": [
          {
            "kind": "bar",
            "w": 60,
            "thick": 8,
            "round": false,
            "radius": 0,
            "cx": -62,
            "cy": -52
          },
          {
            "kind": "bar",
            "w": 60,
            "thick": 8,
            "round": false,
            "radius": 0,
            "cx": 62,
            "cy": -52
          }
        ],
        "mouth": {
          "kind": "bar",
          "w": 52,
          "thick": 10,
          "round": false,
          "radius": 0,
          "cy": 44
        },
        "motion": {
          "blinkMs": 0,
          "shutMs": 300,
          "breatheMs": 3600,
          "breatheFrom": -2,
          "breatheTo": 4,
          "spinMs": 0
        }
      }
    }
  }
};

/* The picker's order, and the order the wire uses. `classic` is index 0 because
   it is the firmware's fallback when NVS names a set it does not have. */
export const FACE_SET_IDS = [
  "classic",
  "bloom",
  "bmo",
  "pixel"
];

/* All eight. `asleep` is a real state with its own geometry and motion, not a
   modifier applied to another one. */
export const FACE_STATES = [
  "neutral",
  "happy",
  "sleepy",
  "surprised",
  "sad",
  "sick",
  "dead",
  "asleep"
];

/* The five the PHONE may draw. `sleepy` and `surprised` are written by the
   phone, decay on the device and are never reported back, so the app cannot
   know when one is showing and does not guess — rule 2, never assert what we
   have not been told. `asleep` is the pet's own and travels no better. */
export const APP_DRAWN_STATES = [
  "happy",
  "neutral",
  "sad",
  "sick",
  "dead"
];
