package com.digitalpet.llm

/**
 * Roles that a [Message] participant can assume within a conversation.
 */
enum class MessageRole {
    /** The invisible system instruction that shapes the assistant's behaviour. */
    SYSTEM,

    /** A message authored by the human user. */
    USER,

    /** A message generated by the LLM assistant. */
    ASSISTANT
}

/**
 * A single message in a conversation.
 *
 * @property role      the role of the message author.
 * @property content   the textual content of the message.
 * @property timestamp epoch-millisecond timestamp when the message was created.
 */
data class Message(
    val role: MessageRole,
    val content: String,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Represents a single notification captured from the device's notification stream.
 *
 * Used by [SystemPromptManager] to build summary prompts so the pet can
 * react to real-world events.
 *
 * @property appName   package name or label of the originating app.
 * @property title     notification title text.
 * @property text      notification body text.
 * @property timestamp epoch-millisecond timestamp of the notification.
 */
data class NotificationData(
    val appName: String,
    val title: String,
    val text: String,
    val timestamp: Long
)
