/* GENERATED by tools/gen-faces.py from design-system/faces/. DO NOT EDIT. */
#pragma once
#include <stdint.h>

/*
 * Every face the pet can wear, in every style it knows.
 *
 * apply_mood() indexes this rather than switching, so adding a style is a
 * data change and the pet's expressions cannot drift between the device and
 * the two surfaces on the phone — all three are generated from the same
 * design-system/faces/ (one JSON file per set).
 *
 * Sizes are device pixels on the 448x368 screen. A mouth_w of 0 means
 * no mouth at all, which is how the dead face is drawn.
 */

/* --- spiral eyes ------------------------------------------------------
 *
 * The face the pet wears when it is ill. Points are x,y pairs in
 * PER-MILLE of the spiral's outer radius, so one table serves every set:
 * scale by eye_w/2 and place at the eye's centre. Nothing here derives a
 * curve — see arc_of() in tools/gen-faces.py for why that arithmetic
 * happens once for all the renderers rather than four times.
 */
#define PET_SPIRAL_STEPS_PER_TURN 24
#define PET_SPIRAL_UNIT 1000

static const int16_t pet_spiral_t2_l[98] = {
    0, 0, 20, 5, 36, 21, 44, 44, 42, 72, 27, 101,
    0, 125, -38, 141, -83, 144, -133, 133, -180, 104, -221, 59,
    -250, 0, -262, -70, -253, -146, -221, -221, -167, -289, -92, -342,
    0, -375, 102, -382, 208, -361, 309, -309, 397, -229, 463, -124,
    500, 0, 503, 135, 469, 271, 398, 398, 292, 505, 156, 584,
    0, 625, -167, 624, -333, 577, -486, 486, -613, 354, -704, 189,
    -750, 0, -745, -200, -686, -396, -575, -575, -417, -722, -221, -825,
    0, -875, 232, -865, 458, -794, 663, -663, 830, -479, 946, -253,
    1000, 0,
};

static const int16_t pet_spiral_t2_r[98] = {
    0, 0, -20, 5, -36, 21, -44, 44, -42, 72, -27, 101,
    0, 125, 38, 141, 83, 144, 133, 133, 180, 104, 221, 59,
    250, 0, 262, -70, 253, -146, 221, -221, 167, -289, 92, -342,
    0, -375, -102, -382, -208, -361, -309, -309, -397, -229, -463, -124,
    -500, 0, -503, 135, -469, 271, -398, 398, -292, 505, -156, 584,
    0, 625, 167, 624, 333, 577, 486, 486, 613, 354, 704, 189,
    750, 0, 745, -200, 686, -396, 575, -575, 417, -722, 221, -825,
    0, -875, -232, -865, -458, -794, -663, -663, -830, -479, -946, -253,
    -1000, 0,
};

#define PET_SPIRAL_MAX_POINTS 49

typedef struct {
    uint8_t turns;
    uint16_t n;
    const int16_t *left;   /* n pairs: x, y */
    const int16_t *right;  /* the same spiral, mirrored */
} pet_spiral_t;

#define PET_SPIRAL_COUNT 1
static const pet_spiral_t pet_spirals[PET_SPIRAL_COUNT] = {
    { 2, 49, pet_spiral_t2_l, pet_spiral_t2_r },
};

/* The table for a face's turn count, or NULL if it has no spiral. A
 * face_geom with eye_spiral_turns of 0 is every face but the sick one. */
static inline const pet_spiral_t *pet_spiral_of(int turns)
{
    for (int i = 0; i < PET_SPIRAL_COUNT; i++) {
        if (pet_spirals[i].turns == turns) {
            return &pet_spirals[i];
        }
    }
    return NULL;
}

typedef struct {
    /* The eyes are allowed to differ. eye_w/h is the LEFT one and
     * eye_rw/rh the right; gaze_x/y moves both off centre, positive y
     * looking down. */
    int16_t eye_w, eye_h, eye_rw, eye_rh;
    int16_t gaze_x, gaze_y;
    /* An eye curves when eye_arc_r is non-zero: its height becomes the
     * stroke thickness and it is drawn as an arc, which is what makes
     * the happy face the classic "^ ^" rather than a flat squint. */
    int16_t eye_arc_r, eye_arc_dy, eye_arc_start, eye_arc_end;
    /* Non-zero when the eyes are SPIRALS: the number of turns, which
     * selects a unit table above. eye_w is then the outer DIAMETER and
     * eye_h the stroke, the same reinterpretation a curved eye makes.
     * The pet spirals when it is ill, and nothing else does. */
    int16_t eye_spiral_turns;
    /* The mouth is a stroke of `mouth_thick` along an arc of chord
     * `mouth_w`. arc_r of 0 means it is straight — a plain capsule,
     * which is what every face was before curves existed.
     *
     * arc_dy is where the CIRCLE's centre goes relative to
     * mouth_off_y, so the chord lands on mouth_off_y and bulges from
     * there. Angles are degrees, 0 at 3 o'clock, clockwise. All of it
     * is computed by the generator: nothing here re-derives geometry. */
    int16_t mouth_w, mouth_thick;
    int16_t arc_r, arc_dy, arc_start, arc_end;
    uint8_t mouth_round;
    /* How this face moves. blink_ms of 0 means it does not blink;
     * breathe_ms of 0 means it does not breathe. Both zero is the dead
     * face, and the absence is the message rather than a special case. */
    int16_t blink_ms, shut_ms;
    int16_t breathe_ms, breathe_from, breathe_to;
    /* Milliseconds per full revolution of a spiral eye. 0 everywhere
     * else — nothing but a spiral turns. */
    int16_t spin_ms;
} pet_face_geom_t;

/* Indexes into pet_face_set_t.face[]. The first seven ARE the PET_MOOD_*
 * values and must stay in that order; asleep is an overlay, not a mood. */
typedef enum {
    PET_FACE_NEUTRAL = 0,
    PET_FACE_HAPPY = 1,
    PET_FACE_SLEEPY = 2,
    PET_FACE_SURPRISED = 3,
    PET_FACE_SAD = 4,
    PET_FACE_SICK = 5,
    PET_FACE_DEAD = 6,
    PET_FACE_ASLEEP = 7,
    PET_FACE_SLOTS = 8,
} pet_face_slot_t;

typedef struct {
    const char *id;      /* stable, stored in NVS and sent on the wire */
    const char *name;    /* shown to a human */
    uint32_t color_eye, color_mouth, color_panel, color_text;
    /* The talk button's fill. C only — the app draws no such
     * control, so a Kotlin copy would be dead. */
    uint32_t color_control;
    int16_t eye_off_x, eye_off_y, mouth_off_y, eye_radius;
    uint8_t stage_pct[4];
    pet_face_geom_t face[PET_FACE_SLOTS];
} pet_face_set_t;

#define PET_FACE_SET_COUNT 4

static const pet_face_set_t pet_face_sets[PET_FACE_SET_COUNT] = {
    {
        .id = "classic",
        .name = "Classic",
        .color_eye = 0xF5A623, .color_mouth = 0xF5A623,
        .color_panel = 0x000000, .color_text = 0xE8E6F0,
        .color_control = 0x14202A,
        .eye_off_x = 64, .eye_off_y = -56,
        .mouth_off_y = 40, .eye_radius = -1,
        .stage_pct = { 55, 70, 85, 100 },
        .face = {
            [PET_FACE_NEUTRAL] = { 74, 96, 74, 96, 0, 0, 0, 0, 0, 0, 0, 120, 16, 0, 0, 0, 0, 1, 5400, 300, 1900, -4, 6, 0 },
            [PET_FACE_HAPPY] = { 74, 14, 74, 14, 0, -3, 51, 35, 223, 317, 0, 150, 22, 151, -131, 60, 120, 1, 6200, 300, 2300, -5, 8, 0 },
            [PET_FACE_SLEEPY] = { 74, 16, 74, 16, 0, 5, 0, 0, 0, 0, 0, 56, 10, 0, 0, 0, 0, 1, 9000, 300, 3200, -3, 5, 0 },
            [PET_FACE_SURPRISED] = { 88, 112, 88, 112, 0, -2, 0, 0, 0, 0, 0, 52, 52, 0, 0, 0, 0, 1, 8000, 300, 1200, -1, 2, 0 },
            [PET_FACE_SAD] = { 74, 62, 74, 62, 0, 7, 0, 0, 0, 0, 0, 80, 12, 104, 96, 247, 293, 1, 7000, 300, 2600, -3, 4, 0 },
            [PET_FACE_SICK] = { 76, 10, 72, 11, 0, 4, 0, 0, 0, 0, 2, 40, 40, 0, 0, 0, 0, 1, 3200, 300, 900, -2, 3, 2600 },
            [PET_FACE_DEAD] = { 74, 8, 74, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 },
            [PET_FACE_ASLEEP] = { 74, 8, 74, 8, 0, 0, 0, 0, 0, 0, 0, 56, 10, 0, 0, 0, 0, 1, 0, 300, 3600, -2, 4, 0 },
        },
    },
    {
        .id = "bloom",
        .name = "Bloom",
        .color_eye = 0xFF8FA3, .color_mouth = 0xFFC2CD,
        .color_panel = 0x140A0F, .color_text = 0xFFE4EA,
        .color_control = 0x2A1A20,
        .eye_off_x = 56, .eye_off_y = -44,
        .mouth_off_y = 48, .eye_radius = -1,
        .stage_pct = { 55, 70, 85, 100 },
        .face = {
            [PET_FACE_NEUTRAL] = { 84, 88, 84, 88, 0, 0, 0, 0, 0, 0, 0, 104, 20, 0, 0, 0, 0, 1, 5400, 300, 1900, -4, 6, 0 },
            [PET_FACE_HAPPY] = { 84, 16, 84, 16, 0, -3, 58, 40, 224, 316, 0, 156, 20, 130, -104, 53, 127, 1, 6200, 300, 2300, -5, 8, 0 },
            [PET_FACE_SLEEPY] = { 84, 18, 84, 18, 0, 5, 0, 0, 0, 0, 0, 60, 14, 0, 0, 0, 0, 1, 9000, 300, 3200, -3, 5, 0 },
            [PET_FACE_SURPRISED] = { 96, 116, 96, 116, 0, -2, 0, 0, 0, 0, 0, 56, 56, 0, 0, 0, 0, 1, 8000, 300, 1200, -1, 2, 0 },
            [PET_FACE_SAD] = { 84, 66, 84, 66, 0, 7, 0, 0, 0, 0, 0, 80, 16, 85, 75, 242, 298, 1, 7000, 300, 2600, -3, 4, 0 },
            [PET_FACE_SICK] = { 80, 12, 74, 11, 0, 4, 0, 0, 0, 0, 2, 44, 44, 0, 0, 0, 0, 1, 3200, 300, 900, -2, 3, 2600 },
            [PET_FACE_DEAD] = { 84, 10, 84, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 },
            [PET_FACE_ASLEEP] = { 84, 10, 84, 10, 0, 0, 0, 0, 0, 0, 0, 60, 14, 0, 0, 0, 0, 1, 0, 300, 3600, -2, 4, 0 },
        },
    },
    {
        .id = "bmo",
        .name = "Little Computer",
        .color_eye = 0x14332B, .color_mouth = 0x14332B,
        .color_panel = 0xAEDCC8, .color_text = 0x14332B,
        .color_control = 0xE8F5EE,
        .eye_off_x = 64, .eye_off_y = -34,
        .mouth_off_y = 46, .eye_radius = -1,
        .stage_pct = { 55, 70, 85, 100 },
        .face = {
            [PET_FACE_NEUTRAL] = { 38, 38, 38, 38, 0, 0, 0, 0, 0, 0, 0, 44, 10, 0, 0, 0, 0, 1, 4200, 260, 1700, -3, 5, 0 },
            [PET_FACE_HAPPY] = { 38, 9, 38, 9, 0, -3, 23, 13, 214, 326, 0, 74, 10, 51, -35, 43, 137, 1, 5200, 260, 2000, -4, 7, 0 },
            [PET_FACE_SLEEPY] = { 38, 10, 38, 10, 0, 5, 0, 0, 0, 0, 0, 30, 8, 0, 0, 0, 0, 1, 8000, 260, 3000, -2, 4, 0 },
            [PET_FACE_SURPRISED] = { 48, 54, 48, 54, 0, -2, 0, 0, 0, 0, 0, 34, 34, 0, 0, 0, 0, 1, 7000, 260, 1100, -1, 2, 0 },
            [PET_FACE_SAD] = { 38, 28, 38, 28, 0, 7, 0, 0, 0, 0, 0, 48, 10, 36, 28, 229, 311, 1, 6400, 260, 2400, -2, 4, 0 },
            [PET_FACE_SICK] = { 50, 8, 44, 7, 0, 4, 0, 0, 0, 0, 2, 30, 30, 0, 0, 0, 0, 1, 2800, 260, 850, -1, 2, 2400 },
            [PET_FACE_DEAD] = { 38, 6, 38, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 },
            [PET_FACE_ASLEEP] = { 38, 7, 38, 7, 0, 0, 0, 0, 0, 0, 0, 30, 8, 0, 0, 0, 0, 1, 0, 260, 3400, -2, 4, 0 },
        },
    },
    {
        .id = "pixel",
        .name = "Pixel",
        .color_eye = 0x9BE564, .color_mouth = 0x9BE564,
        .color_panel = 0x0B1400, .color_text = 0xD6F5B8,
        .color_control = 0x16240A,
        .eye_off_x = 62, .eye_off_y = -52,
        .mouth_off_y = 44, .eye_radius = 0,
        .stage_pct = { 55, 70, 85, 100 },
        .face = {
            [PET_FACE_NEUTRAL] = { 60, 84, 60, 84, 0, 0, 0, 0, 0, 0, 0, 112, 16, 0, 0, 0, 0, 0, 5400, 300, 1900, -4, 6, 0 },
            [PET_FACE_HAPPY] = { 60, 12, 60, 12, 0, -3, 39, 25, 220, 320, 0, 144, 16, 140, -120, 59, 121, 0, 4000, 300, 1400, -4, 6, 0 },
            [PET_FACE_SLEEPY] = { 60, 14, 60, 14, 0, 5, 0, 0, 0, 0, 0, 52, 10, 0, 0, 0, 0, 0, 9000, 300, 3200, -3, 5, 0 },
            [PET_FACE_SURPRISED] = { 76, 104, 76, 104, 0, -2, 0, 0, 0, 0, 0, 48, 48, 0, 0, 0, 0, 0, 8000, 300, 1200, -1, 2, 0 },
            [PET_FACE_SAD] = { 60, 56, 60, 56, 0, 7, 0, 0, 0, 0, 0, 68, 12, 76, 68, 244, 296, 0, 7000, 300, 2600, -3, 4, 0 },
            [PET_FACE_SICK] = { 64, 10, 58, 9, 0, 4, 0, 0, 0, 0, 2, 36, 36, 0, 0, 0, 0, 1, 3200, 300, 900, -2, 3, 2800 },
            [PET_FACE_DEAD] = { 60, 8, 60, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            [PET_FACE_ASLEEP] = { 60, 8, 60, 8, 0, 0, 0, 0, 0, 0, 0, 52, 10, 0, 0, 0, 0, 0, 0, 300, 3600, -2, 4, 0 },
        },
    },
};
