package com.digitalpet.pet

import androidx.compose.ui.graphics.Color
import com.digitalpet.R
import com.digitalpet.ble.PetProtocol

// GENERATED by tools/gen-faces.py from design-system/faces/. DO NOT EDIT.

/**
 * Every face set the pet knows, generated from `design-system/faces/`.
 *
 * The pet, this app's panel and the notification icon all draw from these
 * numbers, so the thing on the shelf and the thing in your hand cannot
 * disagree — which is what [PetFace] used to guarantee by being checked
 * against the firmware, and now guarantees by being generated with it.
 *
 * Sizes are device pixels on the 448x368 screen; callers scale.
 */
/**
 * The spiral the pet's eyes become when it is ill.
 *
 * Points are x, y pairs in PER-MILLE of the spiral's outer radius —
 * one curve for every set, scaled by each eye's own radius. Generated
 * with the firmware's own tables so the pet in your hand and the pet on
 * the shelf wind the same way.
 */
object PetSpirals {
    const val STEPS_PER_TURN = 24
    const val UNIT = 1000

    private val T2_L = intArrayOf(
        0, 0, 20, 5, 36, 21, 44, 44, 42, 72, 27, 101,
        0, 125, -38, 141, -83, 144, -133, 133, -180, 104, -221, 59,
        -250, 0, -262, -70, -253, -146, -221, -221, -167, -289, -92, -342,
        0, -375, 102, -382, 208, -361, 309, -309, 397, -229, 463, -124,
        500, 0, 503, 135, 469, 271, 398, 398, 292, 505, 156, 584,
        0, 625, -167, 624, -333, 577, -486, 486, -613, 354, -704, 189,
        -750, 0, -745, -200, -686, -396, -575, -575, -417, -722, -221, -825,
        0, -875, 232, -865, 458, -794, 663, -663, 830, -479, 946, -253,
        1000, 0,
    )

    private val T2_R = intArrayOf(
        0, 0, -20, 5, -36, 21, -44, 44, -42, 72, -27, 101,
        0, 125, 38, 141, 83, 144, 133, 133, 180, 104, 221, 59,
        250, 0, 262, -70, 253, -146, 221, -221, 167, -289, 92, -342,
        0, -375, -102, -382, -208, -361, -309, -309, -397, -229, -463, -124,
        -500, 0, -503, 135, -469, 271, -398, 398, -292, 505, -156, 584,
        0, 625, 167, 624, 333, 577, 486, 486, 613, 354, 704, 189,
        750, 0, 745, -200, 686, -396, 575, -575, 417, -722, 221, -825,
        0, -875, -232, -865, -458, -794, -663, -663, -830, -479, -946, -253,
        -1000, 0,
    )

    /** The unit spiral of [turns] turns for [side] (0 is the left eye),
     *  or null when no set winds that many — which is what a face with
     *  ordinary eyes asks for, with turns of 0. */
    fun points(turns: Int, side: Int): IntArray? = when (turns) {
        2 -> if (side == 0) T2_L else T2_R
        else -> null
    }
}

data class PetFaceGeometry(
    val eyeWidth: Int,
    val eyeHeight: Int,
    /** The right eye may differ from the left — an asymmetric face
     *  reads as queasy in a way two identical eyes cannot. On the sick
     *  face, which is the one that uses it, these size the smaller and
     *  heavier of its two spirals. */
    val rightEyeWidth: Int,
    val rightEyeHeight: Int,
    /** Both eyes off centre. Positive [gazeY] looks DOWN, matching the
     *  screen's own axis rather than inventing a second convention. */
    val gazeX: Int,
    val gazeY: Int,
    /** Non-zero when the eyes curve — the height is then the stroke
     *  thickness, and the happy face reads as "^ ^". */
    val eyeArcRadius: Int,
    val eyeArcCenterDy: Int,
    val eyeArcStart: Int,
    val eyeArcEnd: Int,
    /** Non-zero when the eyes are SPIRALS, and how many turns they
     *  wind. [eyeWidth] is then the outer DIAMETER and [eyeHeight] the
     *  stroke — the same reinterpretation a curved eye makes. The pet
     *  spirals when it is ill, and nothing else does. */
    val eyeSpiralTurns: Int,
    /** The mouth's chord. Zero means no mouth — the dead face. */
    val mouthWidth: Int,
    /** Stroke thickness along that chord. */
    val mouthThickness: Int,
    /**
     * Radius of the circle the mouth is an arc of, or **0 for a
     * straight bar** — which is a plain capsule, what every face was
     * before curves existed.
     */
    /** What the set ASKED for: positive smiles, negative frowns, 0 flat.
     *  The radius and angles below are derived from it. */
    val mouthBulge: Int,
    val arcRadius: Int,
    /**
     * Where that circle's centre sits, relative to the mouth's own
     * offset, so the chord lands on it and bulges from there.
     */
    val arcCenterDy: Int,
    /** Degrees, 0 at 3 o'clock, clockwise — Compose's own convention. */
    val arcStart: Int,
    val arcEnd: Int,
    val roundCap: Boolean,
    /** 0 means this face does not blink. */
    val blinkMs: Int,
    val shutMs: Int,
    /** 0 means this face does not breathe — the dead one. */
    val breatheMs: Int,
    val breatheFrom: Int,
    val breatheTo: Int,
    /** Milliseconds per full revolution of a spiral eye; 0 for every
     *  other face, because nothing but a spiral turns. */
    val spinMs: Int,
) {
    val hasMouth: Boolean get() = mouthWidth > 0 && mouthThickness > 0

    /** Spiral eyes, drawn from [PetSpirals] rather than as a shape. */
    val isSpiral: Boolean get() = eyeSpiralTurns > 0

    /** The unit spiral for [side] (0 is the left eye), or null. */
    fun spiral(side: Int): IntArray? =
        PetSpirals.points(eyeSpiralTurns, side)

    /** A curve rather than a bar. Every number above is generated, so
     *  this never re-derives anything. */
    val isArc: Boolean get() = arcRadius > 0

    val arcSweep: Int get() = arcEnd - arcStart
}

data class PetFaceSet(
    val id: String,
    val name: String,
    val description: String,
    /**
     * The voice this face suggests, or null. A SUGGESTION: adopted only
     * when the user has never chosen a persona explicitly, because a
     * setting that silently reverted when you changed something else
     * would be worse than no pairing at all.
     */
    val personaId: String?,
    val eyeColor: Color,
    val mouthColor: Color,
    val panelColor: Color,
    val textColor: Color,
    val eyeOffsetX: Int,
    val eyeOffsetY: Int,
    val mouthOffsetY: Int,
    /** -1 means as round as it goes, matching `LV_RADIUS_CIRCLE`. */
    val eyeRadius: Int,
    val stageScaleEgg: Int,
    val stageScaleChild: Int,
    val stageScaleTeen: Int,
    val stageScaleAdult: Int,
    private val faces: Map<PetFace, PetFaceGeometry>,
    /**
     * One drawable per face, because RemoteViews cannot draw — it can only
     * be handed a resource id. Generated from the same numbers the panel
     * scales, so the notification cannot drift from the pet.
     */
    private val notificationIcons: Map<PetFace, Int>,
) {
    /** The geometry this set draws [face] with. */
    operator fun get(face: PetFace): PetFaceGeometry = faces.getValue(face)

    /** The notification avatar for [face] in this set. */
    fun notificationIcon(face: PetFace): Int = notificationIcons.getValue(face)

    /**
     * **The pet grows.** `stage_pct` in the firmware: every expression
     * inherits it, so an egg's happy face and an adult's happy face are the
     * same face at different sizes.
     *
     * Applied to the eye and mouth SIZES only, never to the offsets or the
     * radii — the face shrinks within a panel that does not.
     *
     * An unknown stage draws full size rather than shrinking to an egg:
     * null means we have not been told, and drawing an egg would assert the
     * pet is newly hatched (§5.0 rule 2, in its most misleading direction).
     */
    fun stageScale(stage: PetProtocol.Stage?): Float = when (stage) {
        PetProtocol.Stage.EGG -> stageScaleEgg / 100f
        PetProtocol.Stage.CHILD -> stageScaleChild / 100f
        PetProtocol.Stage.TEEN -> stageScaleTeen / 100f
        PetProtocol.Stage.ADULT, null -> stageScaleAdult / 100f
    }
}

object PetFaceSets {

    /** Classic — The face the pet has always worn. Gold on black, pill eyes. Its geometry is the firmware's own apply_mood() as it stood at protocol v8, with one deliberate change: happy now curves up and sad curves down, because a face set has to mean what it says. */
    val CLASSIC = PetFaceSet(
        id = "classic",
        name = "Classic",
        description = "The face the pet has always worn. Gold on black, pill eyes. Its geometry is the firmware's own apply_mood() as it stood at protocol v8, with one deliberate change: happy now curves up and sad curves down, because a face set has to mean what it says.",
        personaId = "classic",
        eyeColor = Color(0xFFF5A623),
        mouthColor = Color(0xFFF5A623),
        panelColor = Color(0xFF000000),
        textColor = Color(0xFFE8E6F0),
        eyeOffsetX = 64,
        eyeOffsetY = -56,
        mouthOffsetY = 40,
        eyeRadius = -1,
        stageScaleEgg = 55,
        stageScaleChild = 70,
        stageScaleTeen = 85,
        stageScaleAdult = 100,
        faces = mapOf(
            PetFace.HAPPY to PetFaceGeometry(74, 14, 74, 14, 0, -3, 51, 35, 223, 317, 0, 150, 22, 20, 151, -131, 60, 120, true, 6200, 300, 2300, -5, 8, 0),
            PetFace.NEUTRAL to PetFaceGeometry(74, 96, 74, 96, 0, 0, 0, 0, 0, 0, 0, 120, 16, 0, 0, 0, 0, 0, true, 5400, 300, 1900, -4, 6, 0),
            PetFace.SAD to PetFaceGeometry(74, 62, 74, 62, 0, 7, 0, 0, 0, 0, 0, 80, 12, -8, 104, 96, 247, 293, true, 7000, 300, 2600, -3, 4, 0),
            PetFace.SICK to PetFaceGeometry(76, 10, 72, 11, 0, 4, 0, 0, 0, 0, 2, 40, 40, 0, 0, 0, 0, 0, true, 3200, 300, 900, -2, 3, 2600),
            PetFace.DEAD to PetFaceGeometry(74, 8, 74, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, true, 0, 0, 0, 0, 0, 0),
        ),
        notificationIcons = mapOf(
            PetFace.HAPPY to R.drawable.pet_face_classic_happy,
            PetFace.NEUTRAL to R.drawable.pet_face_classic_neutral,
            PetFace.SAD to R.drawable.pet_face_classic_sad,
            PetFace.SICK to R.drawable.pet_face_classic_sick,
            PetFace.DEAD to R.drawable.pet_face_classic_dead,
        ),
    )

    /** Bloom — Wide, soft and close-set — a gentler pet. Everything is rounded to the limit and the eyes sit nearer together and lower, which reads as younger without touching the stage scales. */
    val BLOOM = PetFaceSet(
        id = "bloom",
        name = "Bloom",
        description = "Wide, soft and close-set — a gentler pet. Everything is rounded to the limit and the eyes sit nearer together and lower, which reads as younger without touching the stage scales.",
        personaId = "classic",
        eyeColor = Color(0xFFFF8FA3),
        mouthColor = Color(0xFFFFC2CD),
        panelColor = Color(0xFF140A0F),
        textColor = Color(0xFFFFE4EA),
        eyeOffsetX = 56,
        eyeOffsetY = -44,
        mouthOffsetY = 48,
        eyeRadius = -1,
        stageScaleEgg = 55,
        stageScaleChild = 70,
        stageScaleTeen = 85,
        stageScaleAdult = 100,
        faces = mapOf(
            PetFace.HAPPY to PetFaceGeometry(84, 16, 84, 16, 0, -3, 58, 40, 224, 316, 0, 156, 20, 26, 130, -104, 53, 127, true, 6200, 300, 2300, -5, 8, 0),
            PetFace.NEUTRAL to PetFaceGeometry(84, 88, 84, 88, 0, 0, 0, 0, 0, 0, 0, 104, 20, 0, 0, 0, 0, 0, true, 5400, 300, 1900, -4, 6, 0),
            PetFace.SAD to PetFaceGeometry(84, 66, 84, 66, 0, 7, 0, 0, 0, 0, 0, 80, 16, -10, 85, 75, 242, 298, true, 7000, 300, 2600, -3, 4, 0),
            PetFace.SICK to PetFaceGeometry(80, 12, 74, 11, 0, 4, 0, 0, 0, 0, 2, 44, 44, 0, 0, 0, 0, 0, true, 3200, 300, 900, -2, 3, 2600),
            PetFace.DEAD to PetFaceGeometry(84, 10, 84, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, true, 0, 0, 0, 0, 0, 0),
        ),
        notificationIcons = mapOf(
            PetFace.HAPPY to R.drawable.pet_face_bloom_happy,
            PetFace.NEUTRAL to R.drawable.pet_face_bloom_neutral,
            PetFace.SAD to R.drawable.pet_face_bloom_sad,
            PetFace.SICK to R.drawable.pet_face_bloom_sick,
            PetFace.DEAD to R.drawable.pet_face_bloom_dead,
        ),
    )

    /** Little Computer — A tribute to the small game-console character from Adventure Time: dark features on a pale mint screen, round wide-set eyes and a tiny mouth. The one set that inverts the palette — everything else is light on black, and this is black on light, which is the whole reason it reads as a different machine rather than a recolour. */
    val BMO = PetFaceSet(
        id = "bmo",
        name = "Little Computer",
        description = "A tribute to the small game-console character from Adventure Time: dark features on a pale mint screen, round wide-set eyes and a tiny mouth. The one set that inverts the palette — everything else is light on black, and this is black on light, which is the whole reason it reads as a different machine rather than a recolour.",
        personaId = "bmo",
        eyeColor = Color(0xFF14332B),
        mouthColor = Color(0xFF14332B),
        panelColor = Color(0xFFAEDCC8),
        textColor = Color(0xFF14332B),
        eyeOffsetX = 64,
        eyeOffsetY = -34,
        mouthOffsetY = 46,
        eyeRadius = -1,
        stageScaleEgg = 55,
        stageScaleChild = 70,
        stageScaleTeen = 85,
        stageScaleAdult = 100,
        faces = mapOf(
            PetFace.HAPPY to PetFaceGeometry(38, 9, 38, 9, 0, -3, 23, 13, 214, 326, 0, 74, 10, 16, 51, -35, 43, 137, true, 5200, 260, 2000, -4, 7, 0),
            PetFace.NEUTRAL to PetFaceGeometry(38, 38, 38, 38, 0, 0, 0, 0, 0, 0, 0, 44, 10, 0, 0, 0, 0, 0, true, 4200, 260, 1700, -3, 5, 0),
            PetFace.SAD to PetFaceGeometry(38, 28, 38, 28, 0, 7, 0, 0, 0, 0, 0, 48, 10, -9, 36, 28, 229, 311, true, 6400, 260, 2400, -2, 4, 0),
            PetFace.SICK to PetFaceGeometry(50, 8, 44, 7, 0, 4, 0, 0, 0, 0, 2, 30, 30, 0, 0, 0, 0, 0, true, 2800, 260, 850, -1, 2, 2400),
            PetFace.DEAD to PetFaceGeometry(38, 6, 38, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, true, 0, 0, 0, 0, 0, 0),
        ),
        notificationIcons = mapOf(
            PetFace.HAPPY to R.drawable.pet_face_bmo_happy,
            PetFace.NEUTRAL to R.drawable.pet_face_bmo_neutral,
            PetFace.SAD to R.drawable.pet_face_bmo_sad,
            PetFace.SICK to R.drawable.pet_face_bmo_sick,
            PetFace.DEAD to R.drawable.pet_face_bmo_dead,
        ),
    )

    /** Pixel — Square eyes and a blocky mouth — the pet as a handheld from 1998. Proves the shape lever: nothing here changes except eyeRadius, the mouth radii and the palette, and the pet reads as a different device. */
    val PIXEL = PetFaceSet(
        id = "pixel",
        name = "Pixel",
        description = "Square eyes and a blocky mouth — the pet as a handheld from 1998. Proves the shape lever: nothing here changes except eyeRadius, the mouth radii and the palette, and the pet reads as a different device.",
        personaId = "classic",
        eyeColor = Color(0xFF9BE564),
        mouthColor = Color(0xFF9BE564),
        panelColor = Color(0xFF0B1400),
        textColor = Color(0xFFD6F5B8),
        eyeOffsetX = 62,
        eyeOffsetY = -52,
        mouthOffsetY = 44,
        eyeRadius = 0,
        stageScaleEgg = 55,
        stageScaleChild = 70,
        stageScaleTeen = 85,
        stageScaleAdult = 100,
        faces = mapOf(
            PetFace.HAPPY to PetFaceGeometry(60, 12, 60, 12, 0, -3, 39, 25, 220, 320, 0, 144, 16, 20, 140, -120, 59, 121, false, 4000, 300, 1400, -4, 6, 0),
            PetFace.NEUTRAL to PetFaceGeometry(60, 84, 60, 84, 0, 0, 0, 0, 0, 0, 0, 112, 16, 0, 0, 0, 0, 0, false, 5400, 300, 1900, -4, 6, 0),
            PetFace.SAD to PetFaceGeometry(60, 56, 60, 56, 0, 7, 0, 0, 0, 0, 0, 68, 12, -8, 76, 68, 244, 296, false, 7000, 300, 2600, -3, 4, 0),
            PetFace.SICK to PetFaceGeometry(64, 10, 58, 9, 0, 4, 0, 0, 0, 0, 2, 36, 36, 0, 0, 0, 0, 0, true, 3200, 300, 900, -2, 3, 2800),
            PetFace.DEAD to PetFaceGeometry(60, 8, 60, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, false, 0, 0, 0, 0, 0, 0),
        ),
        notificationIcons = mapOf(
            PetFace.HAPPY to R.drawable.pet_face_pixel_happy,
            PetFace.NEUTRAL to R.drawable.pet_face_pixel_neutral,
            PetFace.SAD to R.drawable.pet_face_pixel_sad,
            PetFace.SICK to R.drawable.pet_face_pixel_sick,
            PetFace.DEAD to R.drawable.pet_face_pixel_dead,
        ),
    )

    /** Every set, in the firmware's own table order. */
    val all: List<PetFaceSet> = listOf(CLASSIC, BLOOM, BMO, PIXEL)

    /**
     * What to draw before the pet has told us which set it is using.
     *
     * The firmware falls back to index 0 when NVS names a set it does not
     * have, so this is the same face for the same reason.
     */
    val default: PetFaceSet = CLASSIC

    /** The set with this id, or null — an id from a newer firmware is a
     *  thing the app must survive rather than crash on. */
    fun byId(id: String?): PetFaceSet? = all.firstOrNull { it.id == id }
}
