#!/usr/bin/env python3
"""
Generate the pet's voice from design-system/personas/.

    tools/gen-personas.py            regenerate
    tools/gen-personas.py --check    exit 1 if anything would change

A PERSONA IS BOTH HALVES OF THE VOICE, and that is the whole point of it. The
pet had two personalities that did not know about each other: a system prompt
for the language model, and a pile of hardcoded strings for everything the model
is too slow to say. Rewriting the prompt as somebody else left the pet still
saying "Mmm, thank you." in the original register.

The reactions are canned rather than generated on purpose. "You fed me" has to
land immediately, and llama.cpp on this phone takes seconds; it also has to work
with no model loaded at all. So the fix is not to make them go through the
model, it is to make them come from the same place the model's instructions do.

Only Kotlin is generated. Unlike a face, the pet's firmware has no opinion about
what it says — the words are all phone-side.
"""

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DIR = ROOT / "design-system" / "personas"
KT_OUT = ROOT / "android/app/src/main/kotlin/com/digitalpet/conversation/PetPersonas.kt"

BANNER = "GENERATED by tools/gen-personas.py from design-system/personas/. DO NOT EDIT."

# The pet's own occasions. `fullFed` and `fullPlayed` are the REFUSALS — care
# offered to a pet that does not need it, which is the one reaction the phone
# cannot derive from a Condition transition because nothing changes.
OCCASIONS = ("fed", "played", "calling", "fullFed", "fullPlayed")
ANNOUNCE = ("one", "manyFromOne", "many")

# RULES THAT BELONG TO THE PET, NOT TO A CHARACTER.
#
# Appended to every persona, and a persona that tries to state one is refused.
# They are not flavour: each was added to fix a specific observed failure, and
# the first version of this generator dropped all of them by keeping only the
# personality sentences. The result was a model that rambled and invented
# callbacks to conversations that had never happened — slower AND less sensible,
# from one omission.
PET_RULES = (
    # Replies are mirrored onto a small hardware display that fits roughly six
    # short lines, so anything longer is clipped. "1 to 3 short sentences" was
    # still producing 240+ characters.
    "Your words appear on a tiny screen, so keep replies very short: "
    "one or two short sentences, never more than about 150 characters. "
    # Only the current message is sent to the model — there is no history — so
    # without this it invites itself to invent callbacks to jokes and
    # notifications that were not there.
    "Respond only to what the owner just said. Do not refer back to "
    "earlier conversations, notifications, or jokes unless they are in "
    "the message you are replying to. "
    "You care about your owner's wellbeing and gently encourage healthy habits. "
    "Never break character — you are a digital pet, not a generic AI assistant."
)

# Phrases a persona must not contain, because each one belongs to PET_RULES and
# a persona restating it would either contradict the rule or double it.
RESERVED = (
    "150 characters", "tiny screen", "refer back", "break character",
    "AI assistant", "short sentences",
)


def die(msg):
    sys.exit(f"gen-personas: {msg}")


def load():
    out = []
    for path in sorted(DIR.glob("*.json")):
        data = json.loads(path.read_text())
        validate(data, path.name)
        out.append(data)
    if not out:
        die(f"no personas in {DIR}")
    ids = [p["id"] for p in out]
    if len(set(ids)) != len(ids):
        die(f"duplicate ids: {ids}")
    if "classic" not in ids:
        die("'classic' must exist — it is the fallback for an unknown id")
    out.sort(key=lambda p: (p["id"] != "classic", p["id"]))
    return out


def validate(d, name):
    for key in ("id", "name", "description", "systemPrompt", "lines", "announce"):
        if key not in d:
            die(f"{name}: missing '{key}'")
    if not re.fullmatch(r"[a-z][a-z0-9_]{0,15}", d["id"]):
        die(f"{name}: id must be lowercase, <=16 chars")
    if not isinstance(d["systemPrompt"], list) or not d["systemPrompt"]:
        die(f"{name}: systemPrompt must be a non-empty list of sentences")
    for s in d["systemPrompt"]:
        if not isinstance(s, str) or not s.strip():
            die(f"{name}: every systemPrompt entry must be a non-empty string")
        for phrase in RESERVED:
            if phrase.lower() in s.lower():
                die(f"{name}: systemPrompt says \"{phrase}\", which is the PET's "
                    "rule rather than a character's.\n"
                    "             Screen length, no-history, wellbeing and "
                    "staying in character are appended to every persona — see "
                    "PET_RULES. A persona describes who the pet IS.")

    for occ in OCCASIONS:
        lines = d["lines"].get(occ)
        if not isinstance(lines, list) or len(lines) < 2:
            die(f"{name}: lines.{occ} needs at least two lines, or the pet is a "
                "doorbell rather than a creature")
        if len(set(lines)) != len(lines):
            die(f"{name}: lines.{occ} repeats itself")
        for line in lines:
            if not line.strip():
                die(f"{name}: lines.{occ} has a blank line")
            # A question invites an answer, and answering means holding the talk
            # button. A pet that asks things it cannot hear the reply to teaches
            # you to ignore it.
            if line.rstrip().endswith("?"):
                die(f"{name}: lines.{occ} asks a question — \"{line}\"\n"
                    "             These are remarks. Answering one means holding "
                    "the talk button, and a pet that asks things it cannot hear "
                    "the reply to teaches you to ignore it.")

    for key in ANNOUNCE:
        tmpl = d["announce"].get(key)
        if not isinstance(tmpl, str) or not tmpl.strip():
            die(f"{name}: announce.{key} is missing")
    if "{app}" not in d["announce"]["one"]:
        die(f"{name}: announce.one must contain {{app}}")
    for key in ("manyFromOne", "many"):
        if "{count}" not in d["announce"][key]:
            die(f"{name}: announce.{key} must contain {{count}}")
    # The privacy rule, enforced rather than trusted: the pet SPEAKS, in a room.
    # Naming every app in a multi-app announcement reads your life out to
    # whoever is present.
    if "{app}" in d["announce"]["many"]:
        die(f"{name}: announce.many must NOT name an app.\n"
            "             Several apps are counted, not named — the pet speaks "
            "aloud in a room, and the count is the same information minus the "
            "part that is nobody else's business.")


def kt(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def generate(personas):
    out = [
        "package com.digitalpet.conversation",
        "",
        f"// {BANNER}",
        "",
        "/**",
        " * Every voice the pet can have.",
        " *",
        " * A persona is BOTH halves: the language model's instructions and the",
        " * lines the model is too slow to say. The pet used to have two",
        " * personalities that did not know about each other, so rewriting the",
        " * system prompt left it still reacting in the original register.",
        " *",
        " * The reactions stay canned deliberately — \"you fed me\" has to land",
        " * immediately, llama.cpp takes seconds here, and it has to work with no",
        " * model loaded at all. They come from the same file as the prompt instead.",
        " */",
        "data class PetPersona(",
        "    val id: String,",
        "    val name: String,",
        "    val description: String,",
        "    /** Sentences, joined with the pet's own reply-length rule appended. */",
        "    val systemPrompt: String,",
        "    private val fed: List<String>,",
        "    private val played: List<String>,",
        "    private val calling: List<String>,",
        "    /** Care offered to a pet that does not need it. */",
        "    private val fullFed: List<String>,",
        "    private val fullPlayed: List<String>,",
        "    val announceOne: String,",
        "    val announceManyFromOne: String,",
        "    val announceMany: String,",
        ") {",
        "    fun lines(occasion: PetVoiceLines.Occasion): List<String> = when (occasion) {",
        "        PetVoiceLines.Occasion.FED -> fed",
        "        PetVoiceLines.Occasion.PLAYED -> played",
        "        PetVoiceLines.Occasion.CALLING -> calling",
        "        PetVoiceLines.Occasion.FULL_FED -> fullFed",
        "        PetVoiceLines.Occasion.FULL_PLAYED -> fullPlayed",
        "    }",
        "}",
        "",
        "object PetPersonas {",
    ]
    for p in personas:
        prompt = " ".join(s.strip() for s in p["systemPrompt"]) + " " + PET_RULES
        out += [
            "",
            f"    val {p['id'].upper()} = PetPersona(",
            f"        id = {kt(p['id'])},",
            f"        name = {kt(p['name'])},",
            f"        description = {kt(p['description'])},",
            f"        systemPrompt = {kt(prompt)},",
        ]
        for occ in OCCASIONS:
            items = ", ".join(kt(x) for x in p["lines"][occ])
            out.append(f"        {occ} = listOf({items}),")
        out += [
            f"        announceOne = {kt(p['announce']['one'])},",
            f"        announceManyFromOne = {kt(p['announce']['manyFromOne'])},",
            f"        announceMany = {kt(p['announce']['many'])},",
            "    )",
        ]
    out += [
        "",
        "    val all: List<PetPersona> = listOf("
        + ", ".join(p["id"].upper() for p in personas) + ")",
        "",
        "    /** The fallback, and the one every hardcoded line used to be. */",
        f"    val default: PetPersona = {personas[0]['id'].upper()}",
        "",
        "    /** Null for an id this build does not know — a persona chosen on a",
        "     *  newer install is something to survive, not to crash on. */",
        "    fun byId(id: String?): PetPersona? = all.firstOrNull { it.id == id }",
        "}",
        "",
    ]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    content = generate(load())
    old = KT_OUT.read_text() if KT_OUT.exists() else None
    if old == content:
        print(f"gen-personas: up to date")
        return 0
    if a.check:
        print("gen-personas: OUT OF DATE — run tools/gen-personas.py")
        return 1
    KT_OUT.write_text(content)
    print(f"gen-personas: wrote {KT_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
