package com.digitalpet.ui.theme

import androidx.compose.ui.graphics.Color

val PetGold = Color(0xFFF5A623)
val PetGoldLight = Color(0xFFFFD700)
val PetPurple = Color(0xFF7B61FF)
val PetPurpleLight = Color(0xFFA594FF)

val DarkBackground = Color(0xFF0D0D12)
val DarkSurface = Color(0xFF1A1A24)
val DarkSurfaceVariant = Color(0xFF22222E)
val OnDarkSurface = Color(0xFFE8E6F0)

val ErrorRed = Color(0xFFFF4C4C)
val SuccessGreen = Color(0xFF4CAF50)
val InfoBlue = Color(0xFF2196F3)
val WarningYellow = Color(0xFFFFC107)

val ConsoleGreen = Color(0xFF00FF00)
val ConsoleBg = Color(0xFF000000)

/* ---------------------------------------------------------------------------
 * The rest of Material 3's colour roles.
 *
 * PLACEHOLDER, AND STRUCTURAL RATHER THAN CHOSEN. Only 12 of M3's 36 roles were
 * mapped, so the other 24 fell back to Material's baseline palette — which meant
 * every Card, ModalBottomSheet, dialog, OutlinedTextField border, divider and
 * scrim in this app was rendering in stock Material colours rather than these.
 * That is very likely why components here kept hardcoding colours: the defaults
 * looked wrong, so each one was overridden by hand.
 *
 * Generated by holding hue and chroma in LCh and sweeping L*, which approximates
 * how Material derives a tonal palette (HCT "tone" is CIELAB L*), with chroma
 * reduced until each result is in sRGB gamut. The neutrals take the PURPLE hue
 * at low chroma because the existing #0D0D12 / #1A1A24 are cool and slightly
 * violet; gold-hued neutrals would have warmed the whole app for no reason.
 *
 * REPLACE THESE. When the palette is redesigned, generate the full set with
 * Material Theme Builder from the chosen seeds rather than extending this by
 * hand — the point of filling every role is that the swap is then one file.
 * ------------------------------------------------------------------------- */
val M3PrimaryContainer = Color(0xFF713800)
val M3OnPrimaryContainer = Color(0xFFFFDA9C)
val M3InversePrimary = Color(0xFF8D5000)
val M3SecondaryContainer = Color(0xFF302CC0)
val M3OnSecondaryContainer = Color(0xFFEDD7FF)
val M3TertiaryContainer = Color(0xFF5A4500)
val M3OnTertiaryContainer = Color(0xFFFFE019)
val M3Error = Color(0xFFFFAFA5)
val M3OnError = Color(0xFF6B000B)
val M3ErrorContainer = Color(0xFF960016)
val M3OnErrorContainer = Color(0xFFFFD6CF)
val M3Outline = Color(0xFF948EA0)
val M3OutlineVariant = Color(0xFF494455)
val M3Scrim = Color(0xFF03000B)
val M3InverseSurface = Color(0xFFE4E1EB)
val M3InverseOnSurface = Color(0xFF322F37)
val M3SurfaceDim = Color(0xFF16111D)
val M3SurfaceBright = Color(0xFF3B3744)
val M3SurfaceContainerLowest = Color(0xFF110B1A)
val M3SurfaceContainerLow = Color(0xFF1D1A26)
val M3SurfaceContainer = Color(0xFF211E2A)
val M3SurfaceContainerHigh = Color(0xFF2C2835)
val M3SurfaceContainerHighest = Color(0xFF373340)

/* ---------------------------------------------------------------------------
 * THE LIGHT SCHEME — from the Claude Design main surface, 2026-08-06.
 *
 * **This app had no light theme at all until now.** Theme.kt read
 * `darkTheme: Boolean = true, // Force dark theme for this app`, and
 * `lightColorScheme` was imported and never used. So none of this replaces
 * anything: it is the light half arriving for the first time.
 *
 * THE DARK SCHEME ABOVE IS DELIBERATELY UNTOUCHED. The design's dark screen
 * (2b) turned out to be drawn almost entirely in colours that were already
 * here — #F5A623 is PetGold, #1A1A24 / #22222E / #0D0D12 are the dark
 * surfaces, #A594FF is PetPurpleLight, #FFD700 PetGoldLight, #E8E6F0
 * OnDarkSurface, #FF4C4C ErrorRed. The redesign kept them, so this file kept
 * them too.
 *
 * The character of the light scheme is WARM: paper creams rather than white,
 * a brown-black rather than grey text, and a muted green doing the work that
 * a saturated accent usually would. Gold stays the primary across both.
 */
val LightBackground = Color(0xFFF7F3E3)      // the page
val LightSurface = Color(0xFFFFFDF5)         // cards, the chat sheet
val LightSurfaceVariant = Color(0xFFF3ECD6)  // the text input
val LightMeterEmpty = Color(0xFFEFE7CD)      // an unfilled meter segment
val LightIconButton = Color(0xFFEDE6CE)      // the circular settings button
val LightPetBubble = Color(0xFFF1EBD7)       // what the pet says
val LightHandle = Color(0xFFDFD7BE)          // the sheet's drag handle

/*
 * Three tiers of on-surface, not two. The design uses them for a real
 * hierarchy — heading, label, and the muted trailing chevron — and collapsing
 * them into one "onSurfaceVariant" is what would flatten the whole screen.
 */
val LightOnSurface = Color(0xFF2A2418)       // headings, the pet's name

/**
 * Meter labels, settings subtitles, the care card's secondary line.
 *
 * **Darkened from `#8A8067` on 2026-08-09, and it is the most consequential
 * colour change this palette has had.** §6.1 says this role "carries more of
 * this app's look than `primary` does", and at `#8A8067` it measured
 * **3.31–3.84:1** against a 4.5 requirement — the most-used text colour in the
 * light scheme and the furthest under. `ContrastTest` found it on its first run
 * and pinned it; DESIGN.md §7.7 carried the decision until it was taken.
 *
 * **It is a new value rather than [LightOnSurfaceStrong], deliberately.** The
 * obvious fix was to reuse the `#6B6350` that already existed — and that
 * collapses two of the three on-surface tiers into one, which is precisely what
 * the note above says would flatten the screen. This sits *between* the old
 * value and Strong: the least darkening that clears the bar, with the hierarchy
 * intact. 4.81 on `background`, 5.25 on `surface`, 4.53 on `surfaceVariant`.
 *
 * It is less recessive than it was. That is the cost of the fix and it was
 * chosen with the cost known; see DESIGN.md §7.7.
 */
val LightOnSurfaceVariant = Color(0xFF736A56)

val LightOnSurfaceStrong = Color(0xFF6B6350) // status bar, secondary text
val LightOnSurfaceDeep = Color(0xFF5C5342)   // body copy, and the bar track
val LightOutline = Color(0xFFC3BAA0)         // chevrons, dividers

/*
 * The greens. Two values rather than one because a green that reads as calm on
 * cream is nearly invisible on #1A1A24 — the same semantic, lifted for the
 * dark scheme. Both replace the stock SuccessGreen for anything the DESIGN
 * touches; SuccessGreen itself stays because the pet's firmware link dot is
 * defined against it (see PetColors).
 *
 * **The light green darkened from `#4B7A50` on 2026-08-09**, with
 * [LightOnSurfaceVariant] and [LightCritical] and by the same amount, so the
 * three muted colours keep the relationship they had. It missed 4.5 on
 * `surfaceVariant` alone, at 4.23; it now measures 4.81 / 5.25 / 4.53 across the
 * three light surfaces, which is the same profile the other two land on.
 */
val LightGreen = Color(0xFF48754D)

/**
 * Gold that can be READ, for the light scheme only.
 *
 * `PetGold` `#F5A623` is a **fill** colour. On the light creams it measures
 * about **1.9:1** against a 4.5:1 requirement, so every gold label and every
 * gold icon on a light surface has been failing contrast since the light theme
 * shipped — a `TextButton`, an `OutlinedButton`, the send and microphone icons,
 * the focused field border. The mocks draw it as it renders rather than
 * darkening it quietly, which is how it came to be measured at all.
 *
 * **This value is the design system's own hover gold**, not one invented here,
 * and it clears AA on all three light surfaces: 5.1:1 on `background`, 5.6:1 on
 * `surface`, 4.8:1 on `surfaceVariant`.
 *
 * The alternative was darkening light `primary` itself. That was rejected
 * because `primary` is the identity: your message bubbles, the meters, the
 * usage-bar fill and the FAB are all gold *fills* with dark text on them, and
 * they neither need the change nor survive it — `onPrimary` would have to flip
 * to white and the warm theme would stop being warm. Fills keep the bright
 * gold; only foregrounds take this.
 */
val LightGoldText = Color(0xFF8A5E0F)
val DarkGreen = Color(0xFF6FBF73)

/**
 * Critical, warm-toned for light. The dark scheme keeps `ErrorRed`.
 *
 * **Darkened from `#C0492F` on 2026-08-09**, with [LightOnSurfaceVariant] and
 * [LightGreen]. It was under on two of the three surfaces — 4.46 on
 * `background`, 4.20 on `surfaceVariant` — near enough to look fine and still a
 * failure, which is the whole reason a test computes this rather than a person
 * judging it. Now 4.78 / 5.22 / 4.50.
 */
val LightCritical = Color(0xFFB8462D)

/*
 * The pet's own panel, and it is the SAME IN BOTH THEMES on purpose.
 *
 * This is not a surface colour — it is a picture of a switched-on AMOLED, and
 * that panel is black whatever the phone's theme is doing. Theming it would
 * make the pet change colour when the user changed their phone settings, which
 * is exactly the confusion between "the pet" and "the app" that DESIGN.md §5.0
 * rule 1 exists to prevent.
 */
val PetPanelBlack = Color(0xFF0B0B0B)

/* ---------------------------------------------------------------------------
 * The rest of Material 3's roles for LIGHT.
 *
 * Taken from the design's own warm neutral ladder rather than generated. The
 * mockups already contain a coherent progression — #FFFDF5, #F7F3E3, #F3ECD6,
 * #EDE6CE, #E6DFC7, #E0D8BE, #DCD5BC — which is exactly the shape M3's
 * surfaceContainer* roles want, so using it keeps the components and the
 * screens drawn from one set of values instead of two that nearly agree.
 *
 * ONE DELIBERATE ASYMMETRY WITH DARK: `secondary` is GREEN here and purple
 * there. Purple does not appear anywhere in the light design; green carries the
 * accent work (chips, the "Doing well." headline). Forcing purple in for
 * symmetry would put a colour on screen that the design never uses.
 */
val M3LightPrimaryContainer = Color(0xFFFFE9C2)
val M3LightOnPrimaryContainer = Color(0xFF3A2A00)
val M3LightInversePrimary = Color(0xFFFFD700)
val M3LightSecondaryContainer = Color(0xFFE9F3E6)
val M3LightOnSecondaryContainer = Color(0xFF223B25)
val M3LightTertiaryContainer = Color(0xFFF3ECD6)
val M3LightOnTertiaryContainer = Color(0xFF3A3428)
val M3LightOnError = Color(0xFFFFFFFF)
val M3LightErrorContainer = Color(0xFFFFDAD3)
val M3LightOnErrorContainer = Color(0xFF5C1408)
val M3LightOutlineVariant = Color(0xFFDCD5BC)
val M3LightScrim = Color(0xFF1A1710)
val M3LightInverseSurface = Color(0xFF2A2418)
val M3LightInverseOnSurface = Color(0xFFF7F3E3)
val M3LightSurfaceDim = Color(0xFFE0D8BE)
val M3LightSurfaceBright = Color(0xFFFFFDF5)
val M3LightSurfaceContainerLowest = Color(0xFFFFFDF5)
val M3LightSurfaceContainerLow = Color(0xFFF7F3E3)
val M3LightSurfaceContainer = Color(0xFFF3ECD6)
val M3LightSurfaceContainerHigh = Color(0xFFEDE6CE)
val M3LightSurfaceContainerHighest = Color(0xFFE6DFC7)
